const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.style={setProperty(){}};this.dataset={};this.hidden=false;this.attrs={};this.classList={add(){},remove(){},toggle(){}};this.open=false;this.value='Aga'}set innerHTML(s){this.html=s;this.firstChild=new Element()}get innerHTML(){return this.html||''}append(...x){this.children.push(...x)}replaceChildren(...x){this.children=x}setAttribute(k,v){this.attrs[k]=String(v)}getAttribute(k){return this.attrs[k]}addEventListener(){}querySelectorAll(){return[]}querySelector(){return new Element()}showModal(){this.open=true}close(){this.open=false}focus(){}scrollIntoView(){}getBoundingClientRect(){return{x:0,y:0,width:1000,height:800}}}
const ids={};for(const m of fs.readFileSync('gry/akademia-zarodnikow/index.html','utf8').matchAll(/id="([^"]+)"/g))ids[m[1]]=new Element();const storage=new Map(),old={person:'Aga',people:{Aga:{facts:{'myko-0-0':{best:100,tries:1,wrong:0,weak:false}},complete:['0:0'],stars:100,runs:[],world:0,active:null}}};storage.set('naukogramy.myko.v1',JSON.stringify(old));let clock=0;const ctx={console,document:{getElementById:i=>ids[i],createElement:t=>new Element(t),createElementNS:(_,t)=>new Element(t),createTextNode:t=>({textContent:t}),querySelectorAll:()=>[],querySelector:()=>null,addEventListener(){}},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},location:{search:''},URLSearchParams,matchMedia:q=>({matches:process.argv.includes('--mobile')&&q.includes('max-width')}),performance:{now:()=>clock},requestAnimationFrame(){},setTimeout:f=>{f();return 1},clearTimeout(){}};vm.createContext(ctx);for(const f of ['data.js','adventure.js','art.js','engine.js','app.js'])vm.runInContext(fs.readFileSync('gry/akademia-zarodnikow/'+f,'utf8'),ctx,{filename:f});const run=s=>vm.runInContext(s,ctx);assert(storage.has('naukogramy.myko.v1.backup-before-board'));assert.equal(run('profile().stars'),100);assert.equal(run('completed(0,0)'),true);ids.welcome.close();
run('choosePlace(0)');assert(run('motion !== null'));clock=200;run('animate(200)');assert(run('pos>0 && pos<E.nodeS[0]'));run('choosePlace(0);choosePlace(0);choosePlace(0)');clock=6000;run('animate(6000)');assert.equal(ids.quest.hidden,false);assert(run('motion===null'));
// Finish every mission, including all renderers, then retry one without farming.
run('profile().stars=0;profile().facts={};profile().complete=[];profile().active=null');
for(let w=0;w<6;w++){run('setWorld('+w+')');for(let n=0;n<3;n++){run('choosePlace('+n+')');clock+=6000;run('animate('+clock+')');assert.equal(ids.quest.hidden,false);for(let i=0;i<4;i++){run("{const q=current();draft=['link','sort'].includes(q.type)?[]:[...q.correct];matched=q.type==='link'?q.pairs.map(p=>p[1]):q.type==='sort'?[...q.correct]:[];check();check();next()}");}assert.equal(run('completed('+w+','+n+')'),true);ids.celebrate.close()}}
assert.equal(run('profile().stars'),7200);assert.equal(run('profile().complete.length'),18);run('setWorld(2);startQuest(0)');run('{const q=current();draft=[...q.correct];check()}');assert.equal(run('profile().stars'),7200);run('closeQuest();startQuest(0)');assert.equal(run('solved'),true);
run('closeQuest();choosePlace(2)');assert(run('motion!==null'));run('choosePlace(1)');assert.equal(run('arrival'),1);run('setWorld(3)');assert.equal(run('motion'),null);assert.equal(ids.quest.hidden,true);
// Changing missions suspends unfinished state. Returning restores it.
run('startQuest(0);profile().active.step=1;profile().active.hinted=true;closeQuest();startQuest(1);closeQuest();startQuest(0)');assert.equal(run('profile().active.step'),1);assert.equal(run('profile().active.hinted'),true);run('openBook();worldMap()');
assert.equal(ids.board.attrs.viewBox,process.argv.includes('--mobile')?'0 0 1000 1080':'0 0 1000 800');
console.log('PASS: app startup, backup/migration, continuous movement, repeated clicks, 18 complete missions and 72 UI renderings, no double award, solved-state resume, suspended sessions, world switch cancels motion, Atlas and world map');
