'use strict';
const $=id=>document.getElementById(id),KEY='naukogramy.future-quest.v1';
const types={choice:'Wybierz odpowiedź',gap:'Uzupełnij lukę',drag:'Przeciągnij do luki',order:'Ułóż zdanie',sort:'Rozpoznaj funkcję',fix:'Napraw błąd'};
const hints={will:'Czy to decyzja podjęta teraz, obietnica lub opinia o przyszłości?',going:'Czy decyzja zapadła wcześniej? A może widać oznaki tego, co się wydarzy?',continuous:'Sprawdź, czy plan jest już z kimś uzgodniony lub zarezerwowany.',simple:'Zwróć uwagę na rozkład albo słowa if, when, before, until, as soon as.',shall:'Czy proponujesz wspólne działanie (we), czy oferujesz własną pomoc (I)?'};
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function norm(s){return s.trim().toLowerCase().replace(/[’‘]/g,"'").replace(/\bi['’]m\b/g,'i am').replace(/\bwon't\b/g,'will not').replace(/\bcan't\b/g,'cannot').replace(/\b([a-z]+)'ll\b/g,'$1 will').replace(/\b([a-z]+)'re\b/g,'$1 are').replace(/[.?!,]/g,'').replace(/\s+/g,' ')}
let queue=[],index=0,rows=[],points=0,streak=0,answer='',checked=false,hinted=false,selected=[],bank=[],runId='',mission='all',mode='learn',person='Gaba';
const preferred=read('starytrek.person','Gaba');if([...$('person').options].some(x=>x.value===preferred))$('person').value=preferred;
function show(id){['home','game','result'].forEach(x=>$(x).hidden=x!==id)}
function button(text,action){const b=document.createElement('button');b.type='button';b.textContent=text;b.onclick=action;return b}
function best(){const records=read(KEY,{}),p=$('person').value;const r=records[p]?.['all:'+ $('mode').value];$('record').textContent=r?`Rekord pełnej misji (${p}): ${r.percent}% · ${r.points} energii`:''}
$('person').onchange=()=>{write('starytrek.person',$('person').value);best()};$('mode').onchange=best;best();
function start(which,repeat){mission=String(which);mode=$('mode').value;person=$('person').value;queue=repeat||TASKS.filter(q=>which==='all'||q.level===Number(which));index=0;rows=[];points=0;streak=0;runId=Date.now()+'-'+Math.random().toString(36).slice(2);show('game');render()}
document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>start(b.dataset.start));
function status(){ $('counter').textContent=`Zadanie ${index+1} / ${queue.length}`;$('score').textContent=`⚡ ${points} · seria ${streak}`;$('bar').style.width=(index/queue.length*100)+'%'}
function choose(value,b){if(checked)return;answer=value;document.querySelectorAll('.options button').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});$('check').disabled=false}
function render(){const q=queue[index];answer='';checked=false;hinted=false;selected=[];bank=[];status();$('prompt').textContent=q.prompt;$('taskType').textContent=types[q.type];$('levelLabel').textContent='Etap '+q.level;$('feedback').hidden=true;$('feedback').className='';$('hintText').hidden=true;$('next').hidden=true;$('check').hidden=false;$('check').disabled=true;$('hint').hidden=mode==='exam';$('hint').disabled=false;$('rulesButton').disabled=mode==='exam';const host=$('answerArea');host.replaceChildren();
$('instruction').textContent={choice:'Wybierz formę najlepiej pasującą do kontekstu.',sort:'Rozpoznaj, dlaczego użyto tej formy.',gap:'Wpisz tylko brakującą część zdania.',fix:'Wpisz całe poprawione zdanie.',drag:'Przeciągnij odpowiedź do pola. Na telefonie lub klawiaturą: kliknij odpowiedź, potem pole.',order:'Klikaj słowa w kolejności lub przeciągaj je do pola. Kliknięcie słowa w zdaniu usuwa je.'}[q.type];
if(q.type==='choice'||q.type==='sort'){const area=document.createElement('div');area.className='options';shuffle(q.options).forEach(v=>{const b=button(v,()=>choose(v,b));b.setAttribute('aria-pressed','false');area.append(b)});host.append(area)}
if(q.type==='gap'||q.type==='fix'){const label=document.createElement('label');label.htmlFor='typed';label.textContent=q.type==='gap'?'Brakująca forma':'Poprawne zdanie';const input=document.createElement('input');input.id='typed';input.autocomplete='off';input.spellcheck=false;input.setAttribute('autocapitalize','off');input.oninput=()=>{answer=input.value;$('check').disabled=!answer.trim()};input.onkeydown=e=>{if(e.key==='Enter'&&answer.trim()){e.preventDefault();check()}};host.append(label,input)}
if(q.type==='drag'){let pending='';const area=document.createElement('div');area.className='bank';const slot=button('Upuść odpowiedź tutaj',()=>{if(pending&&!checked){answer=pending;slot.textContent=pending;$('check').disabled=false}});slot.className='slot';slot.setAttribute('aria-label','Pole odpowiedzi: kliknij, aby wstawić wybraną formę');shuffle(q.options).forEach(v=>{const b=button(v,()=>{if(checked)return;pending=v;answer='';$('check').disabled=true;area.querySelectorAll('button').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});slot.textContent='Wstaw: '+v});b.draggable=true;b.setAttribute('aria-pressed','false');b.ondragstart=e=>{pending=v;e.dataTransfer.setData('text/plain',v)};area.append(b)});slot.ondragover=e=>{e.preventDefault();slot.classList.add('over')};slot.ondragleave=()=>slot.classList.remove('over');slot.ondrop=e=>{e.preventDefault();slot.classList.remove('over');if(checked)return;const value=e.dataTransfer.getData('text/plain');if(q.options.includes(value)){pending=value;answer=value;slot.textContent=value;$('check').disabled=false}};host.append(slot,area)}
if(q.type==='order'){bank=shuffle(q.tokens.map((text,id)=>({text,id})));const sentence=document.createElement('div');sentence.className='sentence';sentence.setAttribute('aria-label','Twoje zdanie');const area=document.createElement('div');area.className='bank';function place(id){if(checked||selected.includes(id))return;selected.push(id);paint()}function paint(){sentence.replaceChildren();area.replaceChildren();if(!selected.length){const p=document.createElement('span');p.textContent='Tu powstanie Twoje zdanie';sentence.append(p)}selected.forEach(id=>{const token=bank.find(t=>t.id===id);sentence.append(button(token.text,()=>{if(checked)return;selected=selected.filter(v=>v!==id);paint()}))});bank.forEach(token=>{if(selected.includes(token.id))return;const b=button(token.text,()=>place(token.id));b.draggable=true;b.ondragstart=e=>e.dataTransfer.setData('text/plain',String(token.id));area.append(b)});answer=selected.map(id=>bank.find(t=>t.id===id).text).join(' ');$('check').disabled=selected.length!==bank.length}sentence.ondragover=e=>e.preventDefault();sentence.ondrop=e=>{e.preventDefault();const raw=e.dataTransfer.getData('text/plain');if(raw!==''&&bank.some(t=>t.id===Number(raw)))place(Number(raw))};host.append(sentence,area);paint()}
}
$('hint').onclick=()=>{if(checked)return;hinted=true;$('hintText').textContent=hints[queue[index].rule];$('hintText').hidden=false;$('hint').disabled=true};
function check(){if(checked||!answer.trim())return;const q=queue[index];if(q.type==='order'&&selected.length!==bank.length)return;checked=true;const correct=[q.answer,...(q.accept||[])].some(a=>norm(a)===norm(answer));streak=correct?streak+1:0;const earned=correct?(hinted?6:10)+Math.min(Math.max(streak-1,0),5):0;points+=earned;rows.push({q,answer,correct,hinted});window.StudyActivity?.record(person,`future:${runId}:${q.id}`);status();$('bar').style.width=((index+1)/queue.length*100)+'%';$('answerArea').querySelectorAll('button,input').forEach(x=>x.disabled=true);$('answerArea').querySelectorAll('[draggable]').forEach(x=>x.draggable=false);$('hint').disabled=true;$('check').hidden=true;const f=$('feedback');f.replaceChildren();f.hidden=false;f.className=correct?'':'bad';const title=document.createElement('strong');title.textContent=correct?`Skok udany! +${earned} energii`:'Spokojnie — naprawiamy paradoks.';const sol=document.createElement('p');sol.textContent='Poprawna odpowiedź: '+q.answer;const why=document.createElement('p');why.textContent=q.why||RULES[q.rule][1];const tag=document.createElement('p');tag.textContent=RULES[q.rule][0];f.append(title,sol,why,tag);$('next').textContent=index===queue.length-1?'Zobacz wynik':'Następne zadanie';$('next').hidden=false;$('next').focus()}
$('check').onclick=check;$('next').onclick=()=>{if(!checked)return;if(++index>=queue.length)finish();else render()};$('exit').onclick=()=>{$('rulesButton').disabled=false;show('home');best()};
function finish(){show('result');$('rulesButton').disabled=false;const count=rows.filter(r=>r.correct).length,percent=Math.round(count/rows.length*100),missed=rows.filter(r=>!r.correct);const records=read(KEY,{});records[person]??={};const key=mission+':'+mode,old=records[person][key];if(!old||percent>old.percent||(percent===old.percent&&points>old.points)){records[person][key]={percent,points,at:new Date().toISOString()};write(KEY,records)}const host=$('result');host.replaceChildren();const heading=document.createElement('h1');heading.textContent=percent>=80?'PRZYSZŁOŚĆ ODBLOKOWANA':'JESZCZE JEDEN SKOK';const score=document.createElement('div');score.className='resultscore';score.textContent=percent+'%';const summary=document.createElement('p');summary.textContent=`${count} / ${rows.length} poprawnych · ${points} energii · ${rows.filter(r=>r.hinted).length} podpowiedzi`;const advice=document.createElement('p');advice.textContent=percent>=80?'Dobra robota! Przejrzyj błędy i sprawdź się bez podpowiedzi.':'Najwięcej da teraz powtórka błędów. Wyjaśnienia masz poniżej.';host.append(heading,score,summary,advice);const actions=document.createElement('div');actions.className='actions';actions.append(button('Wybór misji',()=>{show('home');best()}));if(missed.length){const repeat=button('Powtórz błędy · '+missed.length,()=>start('repeat',missed.map(r=>r.q)));repeat.className='primary';actions.append(repeat)}host.append(actions);rows.filter(r=>!r.correct).forEach(r=>{const div=document.createElement('div');div.className='review';const p=document.createElement('p');p.textContent=r.q.prompt;const yours=document.createElement('p');yours.textContent='Twoja odpowiedź: '+r.answer;const right=document.createElement('strong');right.textContent='Poprawnie: '+r.q.answer;const why=document.createElement('p');why.textContent=r.q.why||RULES[r.q.rule][1];div.append(p,yours,right,why);host.append(div)});heading.tabIndex=-1;heading.focus();window.scrollTo({top:0,behavior:'instant'})}
Object.values(RULES).forEach(([title,body,example])=>{const div=document.createElement('div');div.className='rule';const b=document.createElement('b');b.textContent=title;const p=document.createElement('p');p.textContent=body;const em=document.createElement('em');em.textContent=example;div.append(b,p,em);$('ruleList').append(div)});$('rulesButton').onclick=()=>$('rules').showModal();$('closeRules').onclick=()=>$('rules').close();
