'use strict';
const RULES={will:['will / won’t','Decyzja w chwili mówienia, oferta pomocy, obietnica lub przewidywanie oparte na opinii.','I’ll carry your bag. I think it will be sunny.'],going:['be going to','Wcześniejszy zamiar albo przewidywanie na podstawie widocznych oznak.','I’m going to learn Italian. Look! It’s going to fall.'],continuous:['Present Continuous','Uzgodniony plan: umówiona osoba, miejsce, rezerwacja lub bilet.','We’re meeting Alex at six.'],simple:['Present Simple','Rozkład, harmonogram; także po if, when, as soon as, before, after, until w zdaniach o przyszłości.','The train leaves at eight. I’ll call when I arrive.'],shall:['Shall I / Shall we','Propozycja z we lub oferowanie pomocy z I, zwykle w pytaniu.','Shall we order pizza? Shall I open the window?']};
const TASKS=[];
function add(level,type,prompt,answer,rule,extra={}){TASKS.push({id:TASKS.length+1,level,type,prompt,answer,rule,...extra})}
// Original exercises based on the grammatical scope of the supplied Module 4.2 pages.
add(1,'choice','You look tired. ___ carry that box for you.',"I'll",'will',{options:["I'll","I'm carrying","I carry"],why:'To oferta pomocy podjęta w chwili mówienia.'});
add(1,'gap','I think our team ___ (win) tomorrow.','will win','will',{accept:["'ll win"],why:'I think wskazuje tutaj na przewidywanie oparte na opinii.'});
add(1,'drag','Watch that glass! It ___ fall.','is going to','going',{options:['is going to','will','is'],why:'Widać bezpośrednią oznakę: szklanka zaraz spadnie.'});
add(1,'order','Ułóż propozycję: „Może zamówimy pizzę?”','Shall we order pizza?','shall',{tokens:['Shall','we','order','pizza?']});
add(1,'sort','„I promise I’ll keep your secret.” — jaka to funkcja?','Obietnica','will',{options:['Obietnica','Rozkład','Umówiony plan']});
add(1,'fix','Popraw całe zdanie z rozkładu: „The coach will leaves at 9 a.m.”','The coach leaves at 9 a.m.','simple',{why:'W rozkładzie jazdy używamy Present Simple. Nie łączymy will z leaves.'});
add(1,'choice','We have booked a table. We ___ dinner there at seven.','are having','continuous',{options:['are having','have','will have'],why:'Rezerwacja jest dowodem ustalonego planu.'});
add(1,'gap','___ (I / open) the window for you?','Shall I open','shall',{why:'Shall I…? służy do zaoferowania pomocy.'});
add(1,'drag','I have decided: I ___ study more this term.','am going to','going',{options:['am going to','shall','am'],why:'Decyzja już została podjęta, więc to zamiar.'});
add(1,'order','Ułóż zdanie o godzinie odjazdu.','The train leaves at six.','simple',{tokens:['The','train','leaves','at','six.']});
add(1,'sort','„We’re seeing the dentist at four; the appointment is booked.”','Umówiony plan','continuous',{options:['Umówiony plan','Spontaniczna decyzja','Przewidywanie z oznak']});
add(1,'fix','Popraw całe zdanie: „I think it will rains tomorrow.”','I think it will rain tomorrow.','will',{why:'Po will jest podstawowa forma czasownika: rain.'});
add(2,'choice','Those clouds are very dark. It ___ soon.','is going to rain','going',{options:['is going to rain','rains','is raining'],why:'Ciemne chmury są widoczną oznaką.'});
add(2,'gap','The exhibition ___ (open) at ten tomorrow, according to the schedule.','opens','simple');
add(2,'drag','The doorbell is ringing. I ___ it!','will answer','will',{options:['will answer','answer','am answering'],why:'Decyzja zapada teraz, w reakcji na dzwonek.'});
add(2,'order','Ułóż pytanie z propozycją wspólnego wyjścia.','Shall we go out tonight?','shall',{tokens:['Shall','we','go','out','tonight?']});
add(2,'sort','„Look at the cyclist! He’s going to crash!”','Przewidywanie z oznak','going',{options:['Przewidywanie z oznak','Obietnica','Harmonogram']});
add(2,'fix','Popraw całe zdanie: „I’ll text you when I will arrive.”',"I'll text you when I arrive.",'simple',{why:'Po when w takim zdaniu używamy Present Simple.'});
add(2,'choice','We’ve bought the tickets. We ___ to Rome on Friday.','are flying','continuous',{options:['are flying','fly','shall fly'],why:'Bilety potwierdzają ustalony plan podróży.'});
add(2,'gap','I promise I ___ (not / forget) your birthday.',"won't forget",'will',{accept:['will not forget'],why:'Obietnica w przeczeniu: won’t + czasownik.'});
add(2,'drag','I’ll start cooking as soon as Dad ___ home.','gets','simple',{options:['gets','will get','is going to get'],why:'Po as soon as nie używamy tutaj will.'});
add(2,'order','Ułóż zdanie o zamiarze podjętym wcześniej.',"I'm going to learn Spanish.",'going',{tokens:["I'm",'going','to','learn','Spanish.']});
add(2,'sort','„Don’t worry. I’ll help you with the project.”','Oferta pomocy','will',{options:['Oferta pomocy','Rozkład','Widoczne oznaki']});
add(2,'fix','Popraw całe pytanie z propozycją: „Shall we to eat outside?”','Shall we eat outside?','shall',{why:'Po shall używamy czasownika bez to.'});
add(3,'choice','If it ___ tomorrow, we’ll stay indoors.','rains','simple',{options:['rains','will rain','is going to rain'],why:'Po if w pierwszym okresie warunkowym używamy Present Simple.'});
add(3,'gap','We ___ (meet) Nina outside the cinema at 6. We arranged it yesterday.','are meeting','continuous',{accept:["'re meeting"],why:'Uzgodnienie z Niną oznacza ustalony plan.'});
add(3,'drag','The suitcase is too heavy. ___ carry it for you?','Shall I','shall',{options:['Shall I','Shall we','Am I going to'],why:'Oferujesz własną pomoc, dlatego Shall I…?'});
add(3,'order','Ułóż zdanie: „Zadzwonię, gdy skończę”.',"I'll call you when I finish.",'simple',{tokens:["I'll",'call','you','when','I','finish.']});
add(3,'sort','„I’m going to save money for a bike. That’s my plan.”','Wcześniejszy zamiar','going',{options:['Wcześniejszy zamiar','Decyzja w chwili mówienia','Rozkład jazdy']});
add(3,'fix','Popraw całe zdanie: „We won’t leave until the rain will stop.”',"We won't leave until the rain stops.",'simple',{why:'Po until w zdaniu o przyszłości używamy Present Simple; rain to liczba pojedyncza.'});
add(3,'choice','„There’s no milk.” „OK, I ___ some now.”',"'ll buy",'will',{options:["'ll buy",'buy',"'m buying"],why:'To spontaniczna decyzja w odpowiedzi na nową informację.'});
add(3,'gap','Watch out! That shelf ___ (fall) — it’s already moving!','is going to fall','going',{accept:["'s going to fall"],why:'Ruch półki jest bezpośrednią oznaką nadchodzącego zdarzenia.'});
add(3,'drag','We’ll wash our hands before we ___ lunch.','eat','simple',{options:['eat','will eat','are going to eat'],why:'Po before w tym zdaniu o przyszłości jest Present Simple.'});
add(3,'order','Ułóż pytanie o ustalone spotkanie.','Are you meeting Leo tomorrow?','continuous',{tokens:['Are','you','meeting','Leo','tomorrow?']});
add(3,'sort','„The museum closes at five tomorrow.”','Harmonogram','simple',{options:['Harmonogram','Obietnica','Zamiar']});
add(3,'fix','Popraw całe zdanie: „I am going buy a new notebook.”','I am going to buy a new notebook.','going',{accept:["I'm going to buy a new notebook."],why:'Pełna konstrukcja: be + going to + podstawowa forma czasownika.'});
