'use strict';
const $=id=>document.getElementById(id), KEY='gaba-cocina-v1';
let progress={words:{},best:{},coins:0};
try{const p=JSON.parse(localStorage.getItem(KEY));if(p&&typeof p==='object')progress={words:p.words||{},best:p.best||{},coins:Number(p.coins)||0};}catch{}
let session=null,timer=null;
const shuffle=a=>[...a].sort(()=>Math.random()-.5), food=id=>FOODS.find(f=>f.id===id), short=id=>food(id).es.replace(/^(el|la|las|los) /,'');
function save(){try{localStorage.setItem(KEY,JSON.stringify(progress));}catch{}}
function lobby(){clearInterval(timer);timer=null;session=null;document.body.classList.remove('playing');$('lobby').hidden=false;$('game').hidden=true;$('result').hidden=true;$('total').textContent=`🪙 ${progress.coins} monet`;$('levels').innerHTML=MODES.map(m=>`<button class="level" data-mode="${m.id}"><span class="icon">${m.icon}</span><span class="badge">${progress.best[m.id]? '★ '+progress.best[m.id]+'/10':'↗'}</span><small>${m.kicker}</small><strong>${m.title}</strong><p>${m.desc}</p></button>`).join('');$('levels').querySelectorAll('button').forEach(b=>b.onclick=()=>start(b.dataset.mode));$('guestbook').innerHTML=renderGuestbook();$('guestbook').querySelectorAll('[data-guest]').forEach(b=>b.onclick=()=>start('orders',b.dataset.guest));$('words').innerHTML=FOODS.map(f=>{const w=progress.words[f.id]||{ok:0,miss:0};return `<div class="word">${f.emoji} ${f.es} · ${f.pl}<em>${w.ok} poprawnych · ${w.miss} pomyłek</em></div>`}).join('');}
function weighted(pool){const weights=pool.map(f=>{const w=progress.words[f.id]||{ok:0,miss:0};return Math.max(.4,2+Math.min(w.miss,12)*2-Math.min(w.ok,10)*.25)});let n=Math.random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<pool.length;i++){n-=weights[i];if(n<=0)return pool[i];}return pool[0];}
function remember(ids,correct){ids.forEach(id=>{const w=progress.words[id]||{ok:0,miss:0};w[correct?'ok':'miss']++;progress.words[id]=w;});save();}
function start(mode,guestId){clearInterval(timer);session={mode,round:0,correct:0,coins:0,lives:3,deadline:Date.now()+90000,selected:[],answered:false,hinted:false,seen:[],guestQueue:guestId?[GUESTS.find(g=>g.id===guestId),...shuffle(GUESTS.filter(g=>g.id!==guestId))]:shuffle(GUESTS)};document.body.classList.add('playing');$('lobby').hidden=true;$('result').hidden=true;$('game').hidden=false;$('modeTitle').textContent=MODES.find(m=>m.id===mode).title;round();if(mode==='rush')timer=setInterval(()=>{if(session&&session.mode==='rush'){if(Date.now()>=session.deadline)finish();else hud();}},250);}
function hud(){$('score').textContent=session.mode==='rush'?`♥ ${session.lives} · ⏱ ${Math.max(0,Math.ceil((session.deadline-Date.now())/1000))} s · ${session.correct}/10`:`Gość ${session.round+1}/10 · 🪙 ${session.coins}`;$('meterFill').style.width=`${session.round*10}%`;}
function feedback(text,type){$('feedback').textContent=text;$('feedback').className=type||'';}
function uniqueQuestion(arr){let pool=arr.map((v,i)=>({v,i})).filter(o=>!session.seen.includes(o.i));if(!pool.length){session.seen=[];pool=arr.map((v,i)=>({v,i}));}const chosen=shuffle(pool)[0];session.seen.push(chosen.i);return chosen.v;}
function round(){if(!session)return;session.selected=[];session.answered=false;session.hinted=false;session.hintLevel=0;session.boxPhase=false;session.guest=session.guestQueue[session.round%session.guestQueue.length];feedback('','');$('next').hidden=true;$('check').hidden=false;$('check').disabled=false;$('hint').disabled=false;hud();const mode=session.mode;$('hint').hidden=false;document.querySelector('.meter').hidden=false;
if(['stock','orders','rush'].includes(mode)){
 const targets=[];
 if(mode==='stock')targets.push(weighted(FOODS.slice(0,20)).id);
 else targets.push(...guestMeal(session.guest,1+session.round%4),DRINK_FOODS[session.round%DRINK_FOODS.length]);
 session.answer=targets;
 const meal=targets.filter(id=>foodSlot(id)!=='drink'),drink=targets.find(id=>foodSlot(id)==='drink');
 const mealText=meal.length===1?short(meal[0]):short(meal[0])+' con '+meal.slice(1).map(short).join(' y ');
 session.orderText=mode==='stock'?'Necesito '+short(targets[0])+', por favor.':'Quiero '+mealText+' y, para beber, '+short(drink)+', por favor.';
 const pool=mode==='stock'?FOODS.slice(0,20):FOODS.filter(f=>[...MAIN_FOODS,...STARCH_FOODS,...VEG_FOODS].includes(f.id));
 const foodOptions=shuffle([...meal,...shuffle(pool.filter(f=>!meal.includes(f.id))).slice(0,(mode==='stock'?6:10)-meal.length).map(f=>f.id)]);
 session.options=mode==='stock'?foodOptions:[...foodOptions,...DRINK_FOODS];
 $('stage').innerHTML=customer(session.orderText,mode==='stock'?'ZNAJDŹ PRODUKT':'ZAMÓWIENIE')+``+renderKitchen();
 document.querySelectorAll('[data-food]').forEach(b=>{b.onclick=()=>toggleFood(b.dataset.food);b.ondragstart=e=>e.dataTransfer.setData('text/plain',b.dataset.food);});
 for(const target of [$('plate'),$('served-drinks')].filter(Boolean)){target.ondragover=e=>e.preventDefault();target.ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(session.options.includes(id)&&!session.selected.includes(id))toggleFood(id);};}
 plate();
}
else if(mode==='dialog'){session.q=uniqueQuestion(DIALOGS);session.answer=session.q.a;session.orderText=session.q.a.join(' ');session.options=shuffle([...session.q.a,...session.q.d]).map((text,i)=>({text,i}));$('stage').innerHTML=customer(session.q.q,'ROZMOWA PO HISZPAŃSKU')+'<div id="assembled" class="assembled"></div><div id="tiles" class="tiles"></div>';tiles();}
else if(mode==='menu'){session.q=uniqueQuestion(MENU_QUESTIONS);session.answer=session.q[1];session.orderText=session.q[0];const opts=shuffle([DISHES.find(d=>d.id===session.answer),...shuffle(DISHES.filter(d=>d.id!==session.answer)).slice(0,3)]);$('stage').innerHTML=customer(session.orderText)+``+choices(opts.map(d=>({id:d.id,title:d.emoji+' '+d.es,desc:'Lleva: '+d.ingredients})));bindChoices();}
else if(mode==='lunch'){session.q=uniqueQuestion(BOXES);session.answer=session.q.id;session.orderText='Quiero '+session.q.items.slice(0,3).map(short).join(' y ')+'.';$('stage').innerHTML=customer(session.orderText,'DOBIERZ LUNCHBOX')+``+choices(shuffle([session.q,...shuffle(BOXES.filter(b=>b.id!==session.q.id)).slice(0,3)]).map(b=>({id:b.id,title:b.emoji+' '+b.name,desc:'Lleva: '+b.items.map(short).join(', ')})));bindChoices();}
else if(mode==='blogs'){session.q=uniqueQuestion(BLOGS);session.answer=session.q[1];session.orderText=session.q[0];$('stage').innerHTML=customer(session.orderText,'NOWY WPIS W FEEDZIE')+''+choices([{id:'comida',title:'🥗 Comida',desc:'jedzenie'},{id:'viajes',title:'✈️ Viajes',desc:'podróże'},{id:'moda',title:'👗 Moda',desc:'moda'},{id:'bicicletas',title:'🚲 Bicicletas',desc:'rowery'}]);bindChoices();}
$('check').textContent=mode==='stock'?'Sprawdź produkt →':['dialog','blogs'].includes(mode)?'Sprawdź odpowiedź →':'Podaj zamówienie →';}
function choices(opts){return `<div class="choice-grid">${opts.map(o=>`<button class="choice" data-choice="${o.id}">${o.title}<small>${o.desc}</small></button>`).join('')}</div>`;}
function bindChoices(){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(session.answered)return;session.selected=[b.dataset.choice];document.querySelectorAll('[data-choice]').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',String(c===b));});});}
function toggleFood(id){if(!session||session.answered||!session.options.includes(id))return;
 const source=document.querySelector(`[data-food="${id}"]`),box=source?.getBoundingClientRect?.();const origin=box?{x:box.left+box.width/2,y:box.top+box.height/2}:null;
 const at=session.selected.indexOf(id);let replaced=null;
 if(at<0){const slot=foodSlot(id);if(['main','starch','drink'].includes(slot)&&session.mode!=='stock'){replaced=session.selected.find(other=>foodSlot(other)===slot);session.selected=session.selected.filter(other=>foodSlot(other)!==slot);}if(session.mode==='stock')session.selected=[];session.selected.push(id);}else session.selected.splice(at,1);
 plate(id,origin);
 if(replaced)feedback('Zmieniono składnik. Reszta zestawu zostaje.','hint');

}
function plate(changedId,origin){updatePlateVisual(changedId,origin);}
function tiles(){const opts=session.options;$('assembled').innerHTML=session.selected.length?session.selected.map(i=>`<button class="tile" data-return="${i}">${opts[i].text} ×</button>`).join(''):'Twoje zdanie pojawi się tutaj…';$('tiles').innerHTML=opts.filter(o=>!session.selected.includes(o.i)).map(o=>`<button class="tile" data-tile="${o.i}">${o.text}</button>`).join('');document.querySelectorAll('[data-tile]').forEach(b=>b.onclick=()=>{if(!session.answered){session.selected.push(Number(b.dataset.tile));tiles();}});document.querySelectorAll('[data-return]').forEach(b=>b.onclick=()=>{if(!session.answered){session.selected=session.selected.filter(i=>i!==Number(b.dataset.return));tiles();}});}
function check(){if(!session||session.answered)return;if(!session.selected.length){feedback('Najpierw wybierz odpowiedź.','hint');return;}const mode=session.mode;let correct=false,explain='';if(['stock','orders','rush'].includes(mode)){correct=session.selected.length===session.answer.length&&session.answer.every(id=>session.selected.includes(id));explain=session.answer.map(id=>`${food(id).es} = ${food(id).pl}`).join(' · ');remember(session.answer,correct);if(!correct)remember(session.selected.filter(id=>!session.answer.includes(id)),false);}
else if(mode==='dialog'||session.boxPhase){correct=session.selected.map(i=>session.options[i].text).join(' ')===session.answer.join(' ');explain=session.answer.join(' ')+(mode==='dialog'?' — '+session.q.why:'');}
else {correct=session.selected[0]===session.answer;explain=mode==='blogs'?session.q[2]:mode==='menu'?DISHES.find(d=>d.id===session.answer).es+' — '+DISHES.find(d=>d.id===session.answer).pl:session.q.name;}
if(mode==='lunch'&&!session.boxPhase&&correct){session.boxPhase=true;session.selected=[];const a=['Te recomiendo','la comida de '+session.q.name.split(' · ')[0]+',','porque lleva',session.q.items.map(short).join(', ')+'.'];session.answer=a;session.options=shuffle([...a,'No recomiendo','porque no lleva']).map((text,i)=>({text,i}));$('stage').innerHTML=customer('Poleć wybrany lunchbox i wyjaśnij, co zawiera.','REKOMENDACJA')+'<div id="assembled" class="assembled"></div><div id="tiles" class="tiles"></div>';tiles();feedback('Dobry lunchbox! Teraz zbuduj rekomendację.','good');return;}
session.answered=true;let learner='Gaba';try{const chosen=JSON.parse(localStorage.getItem('starytrek.person'));if(['Gaba','Iga','Krzysiek','Aga'].includes(chosen))learner=chosen}catch{}window.StudyActivity?.record(learner,'restaurant:'+(session.activityId??=crypto.randomUUID())+':'+session.round);$('check').hidden=true;$('next').hidden=false;$('hint').disabled=true;if(correct){session.correct++;const reward=session.hinted?5:10;session.coins+=reward;progress.coins+=reward;feedback('¡Muy bien! +'+reward+' monet. '+explain,'good');}else {if(mode==='rush')session.lives--;feedback('Jeszcze to przećwiczymy. Poprawnie: '+explain,'bad');}save();hud();if(mode==='rush'&&session.lives<=0)finish();}
function hint(){if(!session||session.answered)return;session.hinted=true;session.hintLevel=(session.hintLevel||0)+1;const mode=session.mode;let text;
 if(mode==='stock'){const clues={aceite:'Zwróć uwagę na płyn w butelce.',pepino:'Szukaj warzywa o zielonej skórce.',platano:'To owoc, który obierasz przed zjedzeniem.',manzana:'To owoc z pestkami w środku.',yogur:'Szukaj produktu mlecznego w małym opakowaniu.',pan:'To produkt z piekarni.',jamon:'Szukaj produktu mięsnego podawanego w plastrach.',galleta:'To chrupiąca, słodka przekąska.',naranja:'To owoc, który dzieli się na cząstki.',pescado:'Pomyśl o produkcie pochodzącym z wody.',leche:'Szukaj napoju pochodzenia zwierzęcego.',carne:'Szukaj głównego składnika dania, bogatego w białko.',huevo:'Szukaj produktu, który ma skorupkę.',lechuga:'Szukaj liściastego warzywa.',tomate:'Szukaj warzywa używanego też do sosów.',queso:'To produkt mleczny, który można kroić.',arroz:'Zwróć uwagę na drobne ziarna.',fresa:'Szukaj małego owocu z nasionkami na zewnątrz.',mantequilla:'To tłuszcz, którym można posmarować pieczywo.',patata:'To warzywo rosnące pod ziemią.'};text=clues[session.answer[0]]||'Spójrz na kształt i sposób podania produktu. Nie kieruj się samym kolorem.';}
 else if(['orders','rush'].includes(mode)){const n=session.answer.filter(id=>foodSlot(id)!=='drink').length;text=session.hintLevel===1?'Najpierw odczytaj, co jest po „Quiero”. „Con” wprowadza dodatek, a „para beber” — napój.':`Zamówienie obejmuje ${n} ${n===1?'składnik':'składniki'} na talerzu i jeden napój obok. Czy każdy fragment zdania ma swój obrazek?`;}
 else if(mode==='dialog'||session.boxPhase)text=session.hintLevel===1?'Sprawdź liczbę: gusta pasuje do jednej rzeczy lub czynności, gustan do wielu rzeczy. Zwróć uwagę także na przeczenie i częstotliwość.':'Ułóż wypowiedź od osoby i czasownika, potem dodaj czynność lub produkt, a na końcu określenie częstotliwości.';
 else text='Porównaj słowa kluczowe w zamówieniu z dostępnymi odpowiedziami.';
 feedback(text+' · Z podpowiedzią: 5 zamiast 10 monet.','hint');}

function finish(){if(!session)return;document.body.classList.remove('playing');clearInterval(timer);timer=null;const s=session;progress.best[s.mode]=Math.max(Number(progress.best[s.mode])||0,s.correct);save();$('game').hidden=true;$('result').hidden=false;const stars=s.correct>=9?'⭐⭐⭐':s.correct>=6?'⭐⭐':'⭐';$('result').innerHTML=`<div class="trophy">${s.correct>=6?'🏆':'👩‍🍳'}</div><p>ZMIANA ZAKOŃCZONA</p><h2>${stars} ¡Buen trabajo!</h2><p>${s.correct}/10 poprawnych zamówień · ${s.coins} monet</p><p>${s.mode==='rush'&&s.lives<=0?'Skończyły się serduszka.':s.mode==='rush'&&Date.now()>=s.deadline?'Koniec czasu.':''} ${s.correct<6?'Zrób spokojną rundę w magazynie — pomylone słowa wrócą częściej.':'Możesz wybrać kolejną zmianę albo pobić swój wynik.'}</p><button id="again" class="primary">Jeszcze jedna zmiana</button> <button id="home">Wybierz poziom</button>`;$('again').onclick=()=>start(s.mode);$('home').onclick=lobby;session=null;}
$('check').onclick=check;$('hint').onclick=hint;$('next').onclick=()=>{if(!session)return;session.round++;if(session.round>=10)finish();else round();};$('back').onclick=lobby;document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session?.mode==='rush'&&Date.now()>=session.deadline)finish();});lobby();

