'use strict';
document.querySelectorAll('.art').forEach(el=>{const image=document.createElement('div');image.className='art-image';image.setAttribute('aria-hidden','true');el.prepend(image)});
const $=id=>document.getElementById(id),KEY='naukogramy.breaking-kwasy.v1',PEOPLE=['Krzysiek','Gaba','Iga','Aga'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(key,backup)=>{try{return JSON.parse(localStorage.getItem(key))??backup}catch{return backup}};
let saved=read(KEY,{}),person=read('starytrek.person','Krzysiek'),scope='core',run=null,chapter=-1,sound=false,audio=null,storageOK=true;
if(!PEOPLE.includes(person))person='Krzysiek';
const profile=()=>saved[person]||(saved[person]={facts:{},runs:[],active:null});
function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));storageOK=true}catch{storageOK=false}}
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function pool(){return QUESTIONS.filter(q=>scope==='all'||q.core)}
function stage(q){if(q.type==='bottle'||q.id==='test-1')return 0;if(q.type==='build'||q.id==='test-2')return 1;if(/reszt|Budowa/.test(q.tag)||q.id==='extra-iv-ii')return 2;if(/Równania|Otrzymywanie|Bilans/.test(q.tag)||q.id==='test-9')return 3;if(/Zastosowania|Właściwości/.test(q.tag))return 4;return 5}
function setArt(el,n){el.className=el.className.replace(/\bart-\d+\b/g,'').trim()+' art-'+n}
function scene(n){if(n===chapter)return;chapter=n;const c=CHAPTERS[n];['a','b','c'].forEach((key,i)=>{setArt($('story-'+key),c.art[i]);$('caption-'+key).textContent=c.captions[i];$('speech-'+key).textContent=c.speech[i]});setArt($('work-panel'),c.work);$('scene-label').textContent=c.code+' / '+c.title;$('story-heading').textContent='ODCINEK '+String(n+1).padStart(2,'0')+' · '+c.title;$('chapter-dots').innerHTML=CHAPTERS.map((_,i)=>'<i class="'+(i<n?'done':i===n?'current':'')+'"></i>').join('');$('comic').classList.remove('chapter-change');void $('comic').offsetWidth;$('comic').classList.add('chapter-change')}
function show(view){$('comic').dataset.view=view;['lobby','game','result'].forEach(v=>$(v).hidden=v!==view)}
function lobby(){run=null;chapter=-1;scene(0);show('lobby');$('profiles').innerHTML=PEOPLE.map(p=>'<button data-person="'+p+'" aria-pressed="'+(person===p)+'">'+p+'</button>').join('');$('profiles').querySelectorAll('button').forEach(b=>b.onclick=()=>{person=b.dataset.person;try{localStorage.setItem('starytrek.person',JSON.stringify(person))}catch{}lobby()});document.querySelectorAll('[data-scope]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scope===scope)));const p=profile(),known=pool().filter(q=>(p.facts[q.id]?.streak||0)>=2).length,weak=pool().filter(q=>p.facts[q.id]?.weak);$('mastery').textContent=known+'/'+pool().length+' opanowanych · '+weak.length+' do powtórki · zapis w tej przeglądarce';$('weak-start').hidden=!weak.length;$('resume').hidden=!p.active;$('start').textContent=p.active?'NOWY ODCINEK →':'WCHODZĘ W TO →';}
function start(ids){const candidates=ids?QUESTIONS.filter(q=>ids.includes(q.id)):pool();const facts=profile().facts;let questions=[];for(let n=0;n<6;n++){const qs=shuffle(candidates.filter(q=>stage(q)===n));qs.sort((a,b)=>Number(!!facts[b.id]?.weak)-Number(!!facts[a.id]?.weak));questions.push(...qs)}run={id:Date.now()+'-'+Math.random().toString(36).slice(2),scope,ids:questions.map(q=>q.id),index:0,points:0,firstCorrect:0,wrong:[],hinted:[],rows:[],draft:null,review:!!ids};profile().active=run;persist();chapter=-1;show('game');round()}
function current(){return QUESTIONS.find(q=>q.id===run.ids[run.index])}
function draft(){if(!run.draft){const q=current();run.draft={attempts:0,hint:false,solved:false,h:null,residue:null,wrongOptions:[],order:q.a?shuffle(q.a.map((_,i)=>i)):null,residueOrder:q.residues?shuffle(q.residues):null};profile().active=run;persist()}return run.draft}
function bottle(label,color,i){return '<svg viewBox="0 0 110 145" aria-hidden="true"><path d="M39 10h32v14H39z" fill="#263a2b" stroke="#c6d49d" stroke-width="2"/><path d="M43 24v22L23 64v65q0 8 8 8h48q8 0 8-8V64L67 46V24" fill="#76dfdb24" stroke="#b8ece5" stroke-width="3"/><path d="M26 74h58v55q0 5-5 5H31q-5 0-5-5z" fill="'+color+'" opacity=".8"/><path d="M31 60v56" stroke="#edfffa" stroke-width="3" opacity=".7"/><circle cx="70" cy="83" r="4" fill="#deffff99"/><circle cx="60" cy="104" r="3" fill="#deffff99"/><path d="M28 86h54v33H28z" fill="#fff2cc" stroke="#132518" stroke-width="2"/><text x="55" y="108" font-family="system-ui,sans-serif" font-size="'+(label.length>5?'17':'20')+'" font-weight="700" fill="#102218" text-anchor="middle">'+esc(label)+'</text></svg><span>'+'ABCD'[i]+' · wybierz</span>'}
function renderInteraction(){const q=current(),d=draft(),host=$('interaction');host.replaceChildren();if(q.type==='build'){host.innerHTML='<div class="builder"><div class="formula-slot" id="formula-preview"></div><div class="token-row" id="hydrogen-row"><p class="row-name">WODÓR</p>'+[1,2,3].map(n=>'<button class="token" data-h="'+n+'" aria-pressed="'+(d.h===n)+'">'+['','H','H₂','H₃'][n]+'</button>').join('')+'</div><div class="token-row" id="residue-row"><p class="row-name">RESZTA</p>'+d.residueOrder.map(r=>'<button class="token" data-residue="'+r+'" aria-pressed="'+(d.residue===r)+'">'+r+'</button>').join('')+'</div></div>';host.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{if(d.solved)return;d.h=Number(b.dataset.h);persist();updateBuilder()});host.querySelectorAll('[data-residue]').forEach(b=>b.onclick=()=>{if(d.solved)return;d.residue=b.dataset.residue;persist();updateBuilder()});updateBuilder()}else{const box=document.createElement('div');box.className=q.type==='bottle'?'bottle-grid':'choice-grid';d.order.forEach((index,pos)=>{const b=document.createElement('button');b.className=q.type==='bottle'?'bottle':'choice';b.dataset.option=String(index);b.setAttribute('aria-label',q.a[index]);if(q.type==='bottle')b.innerHTML=bottle(q.a[index],['#48d3db','#d7da53','#c98761','#759aca'][pos],pos);else b.innerHTML='<span class="choice-letter">'+'ABCD'[pos]+'.</span>'+esc(q.a[index]);b.disabled=d.solved||d.wrongOptions.includes(index);if(d.wrongOptions.includes(index))b.classList.add('bad');if(d.solved&&index===q.c)b.classList.add('good');b.onclick=()=>answer(index===q.c,q.a[index],index);box.append(b)});host.append(box)}}
function updateBuilder(){const d=draft();$('formula-preview').innerHTML=(d.h?['','H','H₂','H₃'][d.h]:'<small>wybierz H</small>')+(d.residue?esc(d.residue):'<small> + reszta</small>');document.querySelectorAll('[data-h]').forEach(b=>{b.setAttribute('aria-pressed',String(Number(b.dataset.h)===d.h));b.disabled=d.solved});document.querySelectorAll('[data-residue]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.residue===d.residue));b.disabled=d.solved});$('check').disabled=!d.h||!d.residue||d.solved}
function round(){if(run.index>=run.ids.length){finish();return}const q=current(),d=draft();scene(stage(q));show('game');$('chapter-code').textContent=CHAPTERS[chapter].code+' · '+q.tag;$('round-counter').textContent=(run.index+1)+' / '+run.ids.length;$('score-counter').textContent='◆ '+run.points;$('speaker').textContent=run.index%2?'JESSE':'MR. WHITE';const chapterIds=run.ids.filter(id=>stage(QUESTIONS.find(item=>item.id===id))===chapter),position=chapterIds.indexOf(q.id),beat=Math.min(2,Math.floor(position/Math.max(1,chapterIds.length)*3));$('mission-story').textContent=STORY_BEATS[chapter][beat];document.querySelectorAll('.story-panel').forEach((panel,i)=>panel.classList.toggle('current-beat',i===beat));$('question').textContent=q.q;$('hint-copy').hidden=!d.hint;$('hint-copy').textContent=q.hint;$('hint').disabled=d.hint||d.solved;$('hint').hidden=d.solved;$('next').hidden=!d.solved;$('check').hidden=q.type!=='build'||d.solved;$('feedback').hidden=!d.solved&&d.attempts===0;if(!$('feedback').hidden)feedback(d.solved,q);$('progress-fill').style.width=run.index/run.ids.length*100+'%';renderInteraction();$('game').scrollTop=0;persist()}
function feedback(good,q){const d=draft();$('feedback').hidden=false;$('feedback').className='feedback'+(good?'':' bad');$('feedback').innerHTML='<strong>'+esc(good?(d.attempts===1&&!d.hint?'JESSE: „Yo! To jest to.”':'MR. WHITE: „Teraz się zgadza.”'):'MR. WHITE: „Stop. Sprawdź jeszcze raz.”')+'</strong>'+esc(q.e)+(good?'':' Wybierz poprawnie, żeby przejść dalej.');}
function reaction(good){const e=document.createElement('div');e.className='reaction-word'+(good?'':' bad');e.textContent=good?'YEAH!':'HOLD UP!';$('work-panel').append(e);setTimeout(()=>e.remove(),1000)}
function tone(good){if(!sound)return;try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();const t=audio.currentTime;[good?440:140,good?660:110].forEach((hz,i)=>{const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=hz;g.gain.setValueAtTime(.09,t+i*.11);g.gain.exponentialRampToValueAtTime(.001,t+i*.11+.18);o.connect(g).connect(audio.destination);o.start(t+i*.11);o.stop(t+i*.11+.19)})}catch{}}
function answer(good,label,index){const q=current(),d=draft();if(d.solved)return;d.attempts++;window.StudyActivity?.record(person,'bread:'+run.id+':'+q.id);if(!good){if(index!==undefined&&!d.wrongOptions.includes(index))d.wrongOptions.push(index);if(!run.wrong.includes(q.id))run.wrong.push(q.id);profile().facts[q.id]={...(profile().facts[q.id]||{}),weak:true,streak:0};feedback(false,q);renderInteraction();reaction(false);tone(false);persist();return}d.solved=true;const first=d.attempts===1,clean=first&&!d.hint;const points=clean?100:first?70:25;run.points+=points;if(first)run.firstCorrect++;if(d.hint&&!run.hinted.includes(q.id))run.hinted.push(q.id);run.rows.push({id:q.id,first,clean,points,label,attempts:d.attempts});const old=profile().facts[q.id]||{};profile().facts[q.id]={streak:clean?(old.streak||0)+1:0,weak:!clean,last:new Date().toISOString(),tries:(old.tries||0)+d.attempts};persist();feedback(true,q);renderInteraction();$('score-counter').textContent='◆ '+run.points;$('next').hidden=false;$('check').hidden=true;$('hint').hidden=true;reaction(true);tone(true)}
function finish(){const p=profile();if(!p.runs.some(r=>r.id===run.id)){p.runs.push({id:run.id,at:new Date().toISOString(),scope:run.scope,total:run.ids.length,firstCorrect:run.firstCorrect,points:run.points,wrong:run.wrong,hinted:run.hinted,rows:run.rows});p.runs=p.runs.slice(-30)}p.active=null;persist();scene(5);show('result');const pct=Math.round(run.firstCorrect/run.ids.length*100),repeat=[...new Set([...run.wrong,...run.hinted])],topics=[...new Set(repeat.map(id=>QUESTIONS.find(q=>q.id===id).tag))];$('scene-label').textContent='ODCINEK ZAKOŃCZONY / '+person;$('result').innerHTML='<p class="overline">'+esc(person)+' / '+(run.review?'POWTÓRKA':'FINAŁ ODCINKA')+'</p><h2>'+(pct>=90?'CHEMIA OGARNIĘTA.':pct>=60?'JEST BAZA. JEDZIEMY DALEJ.':'WIEMY, CO POPRAWIĆ.')+'</h2><div class="result-stats"><div><strong>'+run.firstCorrect+'/'+run.ids.length+'</strong><span>za pierwszym razem</span></div><div><strong>'+run.points+'</strong><span>z '+run.ids.length*100+' kryształów</span></div><div><strong>'+pct+'%</strong><span>pierwszych trafień</span></div></div><p>'+(repeat.length?'Zostało '+repeat.length+' zadań do powtórki. Wracają te z błędem lub podpowiedzią.':'Wszystkie zadania rozwiązane bez błędów i podpowiedzi.')+'</p>'+(topics.length?'<ul class="result-traps">'+topics.map(t=>'<li>'+esc(t)+'</li>').join(''):'')+'<div class="result-controls">'+(repeat.length?'<button class="comic-button yellow" id="retry">POWTÓRZ TE '+repeat.length+' →</button>':'<button class="comic-button yellow" id="again">NOWY ODCINEK →</button>')+'<button class="comic-button" id="home">DO BAZY</button></div><p class="save-line">'+(storageOK?'Wynik zapisany dla '+esc(person)+' w tej przeglądarce.':'Zapis jest niedostępny. Nie zamykaj tej karty, jeśli chcesz powtórzyć błędy.')+'</p><p class="history-line">Ostatnie odcinki: '+p.runs.slice(-3).reverse().map(r=>r.firstCorrect+'/'+r.total+' · '+r.points+' ◆').join(' / ')+'</p>';$('retry')&&($('retry').onclick=()=>start(repeat));$('again')&&($('again').onclick=()=>start());$('home').onclick=lobby;}
$('start').onclick=()=>start();$('weak-start').onclick=()=>start(pool().filter(q=>profile().facts[q.id]?.weak).map(q=>q.id));$('resume').onclick=()=>{run=profile().active;scope=run.scope;chapter=-1;show('game');round()};$('next').onclick=()=>{if(!draft().solved)return;run.index++;run.draft=null;persist();round()};$('check').onclick=()=>{const d=draft(),q=current();if(!d.h||!d.residue)return;answer(d.h===q.h&&d.residue===q.residue,['','H','H₂','H₃'][d.h]+d.residue)};$('hint').onclick=()=>{const d=draft();if(d.hint||d.solved)return;d.hint=true;persist();$('hint-copy').hidden=false;$('hint-copy').textContent=current().hint;$('hint').disabled=true;$('hint-copy').scrollIntoView({block:'nearest',behavior:'smooth'})};$('pause').onclick=()=>{persist();lobby()};document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{scope=b.dataset.scope;lobby()});
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'♫ ON':'♫ OFF';$('sound').setAttribute('aria-pressed',String(sound));$('sound').setAttribute('aria-label',sound?'Wyłącz dźwięki gry':'Włącz dźwięki gry');if(sound)tone(true)};$('fullscreen').onclick=()=>{if(!document.fullscreenElement)$('comic').requestFullscreen?.().catch(()=>{});else document.exitFullscreen?.().catch(()=>{})};
$('acid-table').innerHTML='<div class="table-wrap"><table><thead><tr><th>Kwas</th><th>Wzór</th><th>Reszta</th><th>Wartościowość</th></tr></thead><tbody>'+ACIDS.map(a=>'<tr><td>'+esc(a.name)+'</td><td>'+a.formula+'</td><td>'+a.residue+'</td><td>'+a.valence+'</td></tr>').join('')+'</tbody></table></div>';$('notebook-button').onclick=()=>{if(run&&!draft().solved){draft().hint=true;persist();$('hint-copy').hidden=false;$('hint-copy').textContent='Skorzystano z zeszytu. To zadanie dostanie punkty jak za podpowiedź.';$('hint').disabled=true}$('notebook').showModal()};
$('brand-home').onclick=()=>{if(run||profile().active){$('brand-dialog').showModal()}else{lobby();$('start').focus()}};
$('brand-continue').onclick=()=>{$('brand-dialog').close()};
$('brand-menu').onclick=()=>{persist();$('brand-dialog').close();lobby();$('resume').hidden?$('start').focus():$('resume').focus()};
$('brand-restart').onclick=()=>{const active=run||profile().active;if(active)scope=active.scope;$('brand-dialog').close();start()};
window.addEventListener('pagehide',persist);lobby();
