'use strict';
const ACIDS=[
{id:'hcl',name:'chlorowodorowy (solny)',formula:'HCl',h:1,residue:'Cl',valence:'I',core:true},
{id:'h2so3',name:'siarkowy(IV)',formula:'H₂SO₃',h:2,residue:'SO₃',valence:'II',core:true},
{id:'h2co3',name:'węglowy',formula:'H₂CO₃',h:2,residue:'CO₃',valence:'II',core:true},
{id:'h2s',name:'siarkowodorowy',formula:'H₂S',h:2,residue:'S',valence:'II'},
{id:'h2so4',name:'siarkowy(VI)',formula:'H₂SO₄',h:2,residue:'SO₄',valence:'II'},
{id:'hno3',name:'azotowy(V)',formula:'HNO₃',h:1,residue:'NO₃',valence:'I'},
{id:'h3po4',name:'fosforowy(V)',formula:'H₃PO₄',h:3,residue:'PO₄',valence:'III'}
];
const ORIGINAL=[
{q:'Który zestaw poprawnie przyporządkowuje wzory trzem kwasom z kartkówki?',a:['chlorowodorowy HCl; siarkowy(IV) H₂SO₃; węglowy(IV) H₂CO₃','chlorowodorowy HClO; siarkowy(IV) H₂SO₄; węglowy(IV) H₂CO₃','chlorowodorowy HCl; siarkowy(IV) H₂SO₄; węglowy(IV) HCO₃','chlorowodorowy H₂Cl; siarkowy(IV) H₂SO₃; węglowy(IV) CO₂'],c:0,e:'HCl to kwas chlorowodorowy (solny), H₂SO₃ to kwas siarkowy(IV), a H₂CO₃ to kwas węglowy(IV). H₂SO₄ to kwas siarkowy(VI); CO₂ jest tlenkiem, nie kwasem.',tag:'Wzory'},
{q:'Skąd bierze się liczba IV w nazwie „kwas siarkowy(IV)”?',a:['Oznacza cztery atomy tlenu w cząsteczce.','Oznacza stopień utlenienia siarki w H₂SO₃.','Oznacza wartościowość wodoru.','Oznacza, że kwas oddaje cztery protony.'],c:1,e:'W H₂SO₃: 2·(+I) + x + 3·(−II) = 0, więc siarka ma stopień utlenienia +IV. Kwasy H₂SO₃ i H₂CO₃ mają po dwa atomy wodoru.',tag:'Nazewnictwo'},
{q:'Jakie równanie opisuje szkolny sposób otrzymywania kwasu siarkowego(IV)?',a:['SO₃ + H₂O → H₂SO₃','SO₂ + H₂O ⇌ H₂SO₃','S + H₂O → H₂SO₃','SO₂ + O₂ → H₂SO₃'],c:1,e:'Tlenek siarki(IV), SO₂, rozpuszcza się w wodzie i tworzy roztwór kwasu siarkowego(IV). Zapis równowagi przypomina, że ten kwas jest nietrwały.',tag:'Otrzymywanie'},
{q:'Uczeń chce otrzymać roztwór kwasu węglowego(IV). Który przebieg doświadczenia jest właściwy?',a:['Przepuszcza CO₂ przez wodę i bada powstały roztwór wskaźnikiem.','Wsypuje suchy węgiel do wody i ogrzewa.','Przepuszcza O₂ przez wodę.','Rozpuszcza CaCO₃ w samej wodzie, zakładając pełną reakcję.'],c:0,e:'Rozpuszczenie CO₂ w wodzie prowadzi do równowagi CO₂ + H₂O ⇌ H₂CO₃. Zakwaszenie można wykazać odpowiednim wskaźnikiem; sam węgiel nie tworzy tak kwasu.',tag:'Doświadczenie'},
{q:'Który zapis jest poprawnym równaniem powstawania kwasu węglowego(IV) w wodzie?',a:['CO + H₂O → H₂CO₃','CO₂ + H₂O ⇌ H₂CO₃','C + 2H₂O → H₂CO₃ + H₂','CO₂ + H₂ → H₂CO₃'],c:1,e:'Bezwodnikiem kwasu węglowego(IV) jest CO₂. Z wodą pozostaje w równowadze z H₂CO₃, którego w roztworze jest tylko część.',tag:'Równania'},
{q:'Do probówki z wodą i wskaźnikiem przepuszczono SO₂. Co najlepiej wyjaśnia zmianę barwy wskaźnika na właściwą dla odczynu kwasowego?',a:['SO₂ jest zasadą i bezpośrednio barwi wskaźnik.','SO₂ reaguje z wodą, a roztwór ma odczyn kwasowy.','Powstaje kwas siarkowy(VI) H₂SO₄ w wyniku samego dodania wody.','Wskaźnik reaguje wyłącznie z tlenem z powietrza.'],c:1,e:'SO₂ + H₂O ⇌ H₂SO₃. Powstały kwaśny roztwór zmienia barwę wskaźnika. Samo dodanie wody do SO₂ nie daje H₂SO₄.',tag:'Doświadczenie'},
{q:'W doświadczeniu powstawania kwasu węglowego(IV) najlepiej porównać próbkę z CO₂ z próbką kontrolną. Co powinna zawierać kontrola?',a:['Tę samą wodę i wskaźnik, ale bez przepuszczania CO₂.','Sam czysty CO₂ bez wody.','Wodę z dużą ilością HCl.','Roztwór H₂SO₄ zamiast wody.'],c:0,e:'Próbka kontrolna różni się tylko badanym czynnikiem, czyli doprowadzeniem CO₂. Dzięki temu zmianę odczynu można powiązać z rozpuszczeniem gazu.',tag:'Doświadczenie'},
{q:'Który opis poprawnie rozróżnia chlorowodór i kwas chlorowodorowy?',a:['To zawsze dwa różne wzory: chlorowodór HClO, kwas HCl.','Chlorowodór to gaz HCl, a kwas chlorowodorowy to jego roztwór wodny.','Chlorowodór to roztwór HCl, a kwas to suchy gaz.','Chlorowodór jest solą, a kwas chlorowodorowy tlenkiem.'],c:1,e:'HCl(g) to gazowy chlorowodór. Po rozpuszczeniu w wodzie otrzymujemy kwas chlorowodorowy, zwyczajowo nazywany kwasem solnym.',tag:'Właściwości'},
{q:'Do roztworu kwasu chlorowodorowego dodano wiórki magnezu. Jakie produkty i obserwację przewidujesz?',a:['MgCl₂ i H₂; pojawiają się pęcherzyki gazu.','MgO i H₂O; roztwór zamarza.','MgSO₃ i CO₂; pojawiają się pęcherzyki.','MgCO₃ i Cl₂; wydziela się zielony gaz.'],c:0,e:'Mg + 2HCl → MgCl₂ + H₂↑. Magnez reaguje z kwasem, a wydzielający się wodór widać jako pęcherzyki.',tag:'Właściwości'},
{q:'Dlaczego po otwarciu napoju gazowanego część rozpuszczonego CO₂ wydostaje się z cieczy?',a:['Kwas węglowy jest nietrwały, a spadek ciśnienia sprzyja ulatnianiu CO₂.','CO₂ zamienia się w tlen wskutek dostępu powietrza.','H₂CO₃ trwale wiąże cały CO₂ po otwarciu.','Woda przekształca się w CO₂.'],c:0,e:'W zamkniętej butelce większe ciśnienie ułatwia utrzymanie CO₂ w roztworze. Po otwarciu gaz się wydziela; równowaga H₂CO₃ ⇌ CO₂ + H₂O przesuwa się.',tag:'Właściwości'},
{q:'Które zestawienie właściwości gazów używanych w doświadczeniach jest poprawne?',a:['SO₂ jest bezbarwny i ma duszący zapach; CO₂ jest bezbarwny i bezwonny.','SO₂ jest niebieski i bezwonny; CO₂ ma duszący zapach.','Oba gazy są barwnymi metalami.','CO₂ ma intensywny zapach zgniłych jaj, a SO₂ nie rozpuszcza się w wodzie.'],c:0,e:'SO₂ jest bezbarwnym gazem o drażniącym, duszącym zapachu; CO₂ jest bezbarwny i bezwonny. SO₂ jest toksyczny — takich gazów nie wącha się bezpośrednio.',tag:'Właściwości'},
{q:'Do wody wapiennej wprowadzono CO₂. Najpierw ciecz zmętniała. Co utworzyło osad?',a:['CaCO₃, zgodnie z Ca(OH)₂ + CO₂ → CaCO₃↓ + H₂O','CaCl₂, zgodnie z Ca(OH)₂ + CO₂ → CaCl₂','H₂SO₃, zgodnie z CO₂ + SO₂ → H₂SO₃','C, ponieważ CO₂ rozpada się na węgiel i tlen'],c:0,e:'Białe zmętnienie to wytrącający się węglan wapnia. Ta reakcja służy do wykrywania CO₂; przy nadmiarze CO₂ osad może się następnie rozpuścić.',tag:'Doświadczenie'},
{q:'Które zastosowanie jest najlepiej powiązane z kwasem chlorowodorowym?',a:['Usuwanie osadów węglanowych preparatem zawierającym HCl.','Nasycanie wody CO₂ w napojach gazowanych.','Bielenie surowców przez SO₂ rozpuszczony w wodzie.','Produkcja tlenu przez rozkład H₂CO₃.'],c:0,e:'HCl reaguje z węglanami, więc bywa składnikiem środków do usuwania kamienia i zapraw. Uwaga praktyczna: nie miesza się takich środków z wybielaczami chlorowymi.',tag:'Zastosowania'},
{q:'Który opis zastosowania kwasu siarkowego(IV) i związanego z nim SO₂ jest najtrafniejszy?',a:['SO₂ i jego roztwory wykorzystywano m.in. do bielenia i konserwowania; gaz wymaga ostrożności.','H₂SO₃ stosuje się jako trwały, czysty materiał budowlany.','H₂SO₃ to główny składnik napojów gazowanych.','SO₂ jest obojętnym gazem używanym do oddychania.'],c:0,e:'Roztwory SO₂ mają właściwości m.in. wybielające i hamujące rozwój drobnoustrojów. Kwas H₂SO₃ jest nietrwały, a sam SO₂ drażniący i toksyczny.',tag:'Zastosowania'},
{q:'Które podsumowanie wszystkich trzech kwasów jest poprawne?',a:['HCl to kwas beztlenowy, a H₂SO₃ i H₂CO₃ to nietrwałe kwasy tlenowe otrzymywane w szkolnych doświadczeniach przez rozpuszczenie odpowiednich tlenków w wodzie.','Wszystkie trzy kwasy są beztlenowe i powstają z metali.','HCl i H₂CO₃ mają identyczny wzór, a H₂SO₃ jest zasadą.','H₂SO₃ powstaje z CO₂, a H₂CO₃ z SO₂.'],c:0,e:'HCl nie zawiera tlenu. H₂SO₃ otrzymuje się z SO₂ i wody, a H₂CO₃ z CO₂ i wody. Oba te kwasy tlenowe są nietrwałe.',tag:'Powtórka'}
];
const QUESTIONS=[];
ACIDS.forEach((acid,i)=>{
const others=ACIDS.filter(a=>a.id!==acid.id);
QUESTIONS.push({id:acid.id+'-bottle',type:'bottle',core:!!acid.core,tag:'Wzory i nazwy',q:'Znajdź butelkę: kwas '+acid.name+'.',a:[acid.formula,...others.slice(i%3,i%3+3).map(a=>a.formula)],c:0,e:acid.formula+' to kwas '+acid.name+'. Reszta '+acid.residue+' ma wartościowość '+acid.valence+'.',hint:'Sprawdź niemetal wskazany w nazwie i czy kwas zawiera tlen.'});
QUESTIONS.push({id:acid.id+'-build',type:'build',core:!!acid.core,tag:'Budowa wzoru',q:'Ułóż wzór kwasu '+acid.name+'. Dobierz wodór i resztę.',answer:acid.formula,h:acid.h,residue:acid.residue,residues:[acid.residue,...others.slice(0,3).map(a=>a.residue)],e:acid.formula+': '+acid.h+' '+(acid.h===1?'atom wodoru':'atomy wodoru')+' i reszta '+acid.residue+'. Wartościowość reszty: '+acid.valence+'.',hint:'Najpierw wybierz właściwą resztę. Liczba atomów H odpowiada jej wartościowości.'});
QUESTIONS.push({id:acid.id+'-residue',type:'choose',core:!!acid.core,tag:'Reszty kwasowe',q:'We wzorze '+acid.formula+' usuń wodór. Jaka pozostaje reszta kwasowa?',a:[acid.residue,...others.slice(0,3).map(a=>a.residue)],c:0,e:'Reszta kwasowa '+acid.formula+' to '+acid.residue+'. Usuń tylko wodór, nie zmieniaj pozostałych indeksów.',hint:'Skreśl H wraz z jego indeksem. Pozostałą część pozostaw bez zmian.'});
QUESTIONS.push({id:acid.id+'-valence',type:'choose',core:!!acid.core,tag:'Wartościowość reszty',q:'Jaka jest wartościowość reszty '+acid.residue+' w kwasie '+acid.formula+'?',a:['I','II','III','IV'],c:['I','II','III','IV'].indexOf(acid.valence),e:'W '+acid.formula+' jest '+acid.h+' '+(acid.h===1?'atom wodoru':'atomy wodoru')+'. Dlatego reszta '+acid.residue+' ma wartościowość '+acid.valence+'.',hint:'Nie licz tlenu. Spójrz na indeks przy H.'});
});
ORIGINAL.forEach((q,i)=>QUESTIONS.push({...q,id:'test-'+(i+1),type:'choose',core:true,hint:q.tag==='Równania'||q.tag==='Otrzymywanie'?'Policz atomy i rozróżnij tlenki. Nie zmieniaj indeksów we wzorze kwasu.':q.tag==='Doświadczenie'?'Oddziel obserwację od wniosku. Próbka kontrolna różni się tylko badanym czynnikiem.':'Porównaj nazwy i wzory. Gaz i jego roztwór wodny to nie to samo.'}));
const EXTRA=[
['oxygen',true,'Podział kwasów','Dwie butelki zawierają kwasy tlenowe. Która para?',['H₂SO₃ i H₂CO₃','HCl i H₂SO₃','HCl i H₂S','H₂O i HCl'],'H₂SO₃ i H₂CO₃ zawierają tlen. HCl i H₂S to kwasy beztlenowe.','Sprawdź symbole pierwiastków, nie liczbę atomów wodoru.'],
['iv-ii',true,'Wartościowość reszty','Jesse miesza IV z II. Co jest prawdą o H₂SO₃?',['Siarka IV; reszta SO₃ — II','Siarka II; reszta SO₃ — IV','Siarka IV; reszta SO₃ — III','Reszta SO₃ — IV, bo IV jest w nazwie'],'IV w nazwie dotyczy siarki. Reszta SO₃ ma wartościowość II, bo kwas zawiera dwa atomy H.','Liczba w nazwie i wartościowość reszty opisują dwie różne rzeczy.'],
['sulfur',true,'Równania','Spalanie siarki daje tlenek do H₂SO₃. Który zapis pasuje?',['S + O₂ → SO₂','S + O₂ → SO₃','S + H₂O → H₂SO₃','SO₃ → S + O₂'],'S + O₂ → SO₂. Dalej, w szkolnym zapisie: SO₂ + H₂O ⇌ H₂SO₃.','Policz atomy siarki i tlenu po obu stronach.'],
['decompose',true,'Równania','Napój traci bąbelki. Dokończ: H₂CO₃ ⇌ …',['H₂O + CO₂','H₂ + CO₃','CO + H₂O','HCl + CO₂'],'Nietrwały kwas węglowy rozkłada się: H₂CO₃ ⇌ H₂O + CO₂.','Produkty mają zachować dwa H, jeden C i trzy O.'],
['balance',true,'Bilans reakcji','Mg + … HCl → MgCl₂ + H₂. Jaki współczynnik brakuje?',['2','1','3','4'],'Mg + 2HCl → MgCl₂ + H₂. Dwa Cl tworzą MgCl₂; dwa H tworzą H₂.','Zacznij od chloru w MgCl₂.'],
['scale',true,'Zastosowania','W myjni osad zawiera CaCO₃. W zadaniu reaguje z HCl. Jaki gaz się wydziela?',['CO₂','O₂','H₂','Cl₂'],'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂. Węglan z kwasem daje sól, wodę i CO₂.','To reakcja z węglanem, a nie z metalem.'],
['nitric',false,'Otrzymywanie','W zeszycie Mr. White’a: N₂O₅ + H₂O → …',['2HNO₃','HNO₃','2HNO₂','H₂NO₃'],'N₂O₅ + H₂O → 2HNO₃. Po obu stronach: 2 N, 2 H, 6 O.','Sprawdź współczynnik. Nie zmieniaj indeksów we wzorze kwasu.'],
['sulfuric',false,'Otrzymywanie','Który zapis pasuje do kwasu siarkowego(VI)?',['SO₃ + H₂O → H₂SO₄','SO₂ + H₂O → H₂SO₄','S + H₂O → H₂SO₄','SO₃ + H₂ → H₂SO₃'],'SO₃ + H₂O → H₂SO₄ to szkolny zapis otrzymywania kwasu siarkowego(VI).','Rozróżnij tlenek siarki(IV) i tlenek siarki(VI).'],
['hygro',false,'Właściwości','H₂SO₄ jest higroskopijny. Co to znaczy?',['Pochłania wodę z otoczenia','Jest niebieskim gazem','Nie rozpuszcza się w wodzie','Ma obojętny odczyn'],'Higroskopijność to pochłanianie wody z otoczenia. Stężony H₂SO₄ ma też właściwości odwadniające.','Słowo dotyczy wilgoci, nie koloru ani odczynu.'],
['battery',false,'Zastosowania','Kamper ma akumulator ołowiowy. Z jakim kwasem kojarzy się elektrolit?',['H₂SO₄','H₂CO₃','H₂SO₃','H₂S'],'Elektrolit akumulatora ołowiowego to roztwór kwasu siarkowego(VI).','Szukasz trwałego kwasu siarkowego, nie kwasu w napoju gazowanym.'],
['fertilizer',false,'Zastosowania','Który kwas wykorzystuje się do produkcji nawozów azotowych?',['HNO₃','H₂CO₃','HCl','H₂S'],'Kwas azotowy(V), HNO₃, służy m.in. do produkcji nawozów azotowych.','Nazwa zastosowania wskazuje pierwiastek. Znajdź jego symbol.'],
['protein',false,'Właściwości','W opisie stężony kwas powoduje żółknięcie białka. Jaki to kwas?',['Azotowy(V)','Węglowy','Siarkowodorowy','Chlorowodorowy'],'To charakterystyczna właściwość stężonego HNO₃, kwasu azotowego(V).','Przypomnij sobie cechę opisaną przy kwasie zawierającym azot.']
];
EXTRA.forEach(([id,core,tag,q,a,e,hint])=>QUESTIONS.push({id:'extra-'+id,type:'choose',core,tag,q,a,c:0,e,hint}));
const CHAPTERS=[
{title:'Zanim ruszymy',code:'01 / DIAGNOZA',art:[0,1,5],work:2,captions:['WIADOMOŚĆ ZE SZPITALA','JESSE MA POMYSŁ','LEKCJE WRACAJĄ'],speech:['Jedna wiadomość wywraca życie Mr. White’a.','Jesse ma kamper. Ty masz ogarnąć chemię.','Najpierw etykiety. Bez tego nie ruszamy.'],story:'Mr. White przypomina sobie lekcje. Jesse znalazł skrzynię bez etykiet.'},
{title:'Kamper na pustyni',code:'02 / PIERWSZY POSTÓJ',art:[1,2,4],work:2,captions:['DALEKO OD MIASTA','STÓŁ W KAMPERZE','KTOŚ NAS WIDZIAŁ'],speech:['„Yo, panie White. To która butelka?”','Nazwy muszą zgadzać się ze wzorami.','Bez paniki. Najpierw chemia.'],story:'Kamper stoi na pustyni. Dopasuj etykiety w szkolnym zadaniu, zanim ruszy następna scena.'},
{title:'Nie pomyl reszty',code:'03 / PODWÓJNA ETYKIETA',art:[2,5,1],work:5,captions:['JESSE MIESZA POJĘCIA','WHITE SPRAWDZA ZESZYT','PRZED DROGĄ'],speech:['„IV w nazwie, to reszta IV?” Nie tak szybko.','„Wodór, Jesse. Spójrz na wodór.”','Liczą się atomy, nie zgadywanie.'],story:'Jesse pomylił liczbę w nazwie z wartościowością reszty. Wyjaśnij to w zeszycie.'},
{title:'Pościg przez pustynię',code:'04 / W DRODZE',art:[4,1,2],work:2,captions:['KURZ I SYRENY','SKOK DO KAMPERA','JEDZIEMY DALEJ'],speech:['Jesse wskakuje do kampera. Syreny zostają w tyle.','„Równania. Licz atomy po obu stronach.”','Na odpowiedź masz tyle czasu, ile potrzebujesz.'],story:'Jesse zatrzaskuje drzwi kampera. Mr. White sprawdza zapis — tu nic nie może się nie zgadzać.'},
{title:'Noc w myjni',code:'05 / SPRAWA OSADU',art:[3,5,4],work:3,captions:['NEONY I WODA','SKYLER LICZY UTARG','JESZCZE JEDNA SPRAWA'],speech:['Skyler trzyma pliki banknotów. Myjnia świeci w ciemności.','Został osad na instalacji. Potrzebne wyjaśnienie.','Właściwości i zastosowania. Teoria robi robotę.'],story:'Skyler zamyka myjnię. Pozostały gazy, osady i pytania o zastosowania kwasów.'},
{title:'Ostatni kadr',code:'06 / WSZYSTKO SIĘ ŁĄCZY',art:[5,2,1],work:5,captions:['NOC W KAMPERZE','JESSE JUŻ KOJARZY','ŚWIT NA PUSTYNI'],speech:['Jeszcze kilka spraw do ogarnięcia.','„Teraz to ma sens.” Wzór, reszta, właściwość.','Kończy się odcinek. Wiedza ma zostać.'],story:'Jesse już nie strzela. Połącz wzory, równania i obserwacje w jedną całość.'}
];
