'use strict';
// Additions have their own IDs. The original 54 IDs and meanings stay unchanged.
const MISSIONS=[
[{art:'microscope',resident:'Myko, odkrywczyni',problem:'Moja lupa pokazuje świat pełen tajemnic. Naucz mnie, jak badać go uczciwie.',effect:'Punkt obserwacji rozświetla się.',card:'Obserwacja i doświadczenie',description:'Obserwacja opisuje; doświadczenie sprawdza wpływ zmienionego czynnika.'},{art:'mushroom',resident:'Nitek, opiekun grzybni',problem:'Pod ściółką czeka pokarm. Pomóż cienkim strzępkom go zdobyć.',effect:'Grzybnia rozrasta się pod ściółką.',card:'Grzybnia',description:'Strzępki tworzą grzybnię. Grzyb trawi na zewnątrz i wchłania produkty.'},{art:'bridge',resident:'Poro, budowniczy mostu',problem:'Most odbudujemy razem. Poznaj współpracę grzyba i partnera fotosyntetyzującego.',effect:'Porostowy most odzyskuje kolor.',card:'Porost',description:'Grzyb współżyje z glonem lub sinicą. Partner fotosyntetyzujący wytwarza pokarm.'}],
[{art:'cell',resident:'Komi, opiekunka komórek',problem:'Brama zgubiła instrukcje. Znajdź właściwe części komórek.',effect:'Brama miasta otwiera się.',card:'Błona i jądro',description:'Błona kontroluje transport. Jądro zawiera DNA; bakterie nie mają jądra.'},{art:'cellhouse',resident:'Chlori, zielony lokator',problem:'W moim domku brakuje zielonego wyposażenia. Pomóż je rozpoznać.',effect:'Zielony domek rozkwita.',card:'Komórka roślinna',description:'Zielona komórka roślinna ma chloroplasty, ścianę i dużą wakuolę.'},{art:'city',resident:'Komi, architektka',problem:'Pojedyncze komórki łączą siły. Zbuduj z nich działający organizm.',effect:'W mieście zapalają się okna.',card:'Od komórki do organizmu',description:'Komórki tworzą tkanki, tkanki organy; organy współpracują w organizmie.'}],
[{art:'mill',resident:'Lumi, młynarka',problem:'Młyn stoi. Rozpoznaj, czego potrzebuje roślina, by wytwarzać pokarm.',effect:'Koło słonecznego młyna zaczyna się obracać.',card:'Fotosynteza',description:'Woda i CO₂, światło oraz chlorofil umożliwiają wytwarzanie glukozy; powstaje tlen.'},{art:'garden',resident:'Listek, ogrodnik',problem:'Wszyscy są głodni. Sprawdź, kto wytwarza pokarm, a kto korzysta z gotowego.',effect:'Ogród wypuszcza nowe liście.',card:'Samożywność i cudzożywność',description:'Roślina wytwarza pokarm. Sole mineralne są potrzebne, ale nie są gotowym pokarmem.'},{art:'lamp',resident:'Lumi, strażniczka latarni',problem:'Zachodzi słońce. Czy komórki mogą nadal zdobywać energię z pokarmu?',effect:'Nocna latarnia zapala się ciepłym światłem.',card:'Oddychanie komórkowe',description:'Uwalnia energię ze związków pokarmowych. Rośliny oddychają w dzień i w nocy.'}],
[{art:'virus',resident:'Viri, wirusowy gość',problem:'Wyglądam jak ludek, lecz nie jestem komórką. Odkryj tę różnicę.',effect:'Wirusowy znak ostrzegawczy rozjaśnia się.',card:'Wirus',description:'Nie ma budowy komórkowej. Do namnażania potrzebuje komórki gospodarza.'},{art:'vial',resident:'Bibi, fermentatorka',problem:'Mikromieszkańcy mają różne zawody. Pomóż znaleźć ich pożyteczne role.',effect:'Pracownia bakterii ożywa.',card:'Bakterie',description:'Jednokomórkowe, bez jądra. Wiele rozkłada szczątki lub pomaga produkować żywność.'},{art:'boat',resident:'Ami, wodna wędrowniczka',problem:'Rzęski, wić czy nibynóżki? Przygotuj naszą wyprawę przez kroplę.',effect:'Łódka i wodne światełka odzyskują blask.',card:'Protisty',description:'Mają komórki z jądrem. Pantofelek używa rzęsek, ameba nibynóżek, euglena wici.'}],
[{art:'root',resident:'Korri, strażnik korzeni',problem:'Krople utknęły w glebie. Znajdź drogę przez korzeń.',effect:'Korzenie zaczynają przewodzić świecące krople.',card:'Korzeń i włośniki',description:'Korzeń umacnia roślinę i pobiera wodę oraz sole mineralne. Włośniki zwiększają powierzchnię.'},{art:'stem',resident:'Łody, przewodnik',problem:'Woda musi dotrzeć wysoko. Odbuduj szlak transportowy.',effect:'Szlak łodygi rozświetla się.',card:'Łodyga i tkanki',description:'Łodyga podtrzymuje organy. Tkanki przewodzące transportują substancje.'},{art:'tower',resident:'Listek, strażnik wieży',problem:'Wieża liści potrzebuje wymiany gazów. Przywróć jej właściwe funkcje.',effect:'Na wieży wyrastają zielone liście.',card:'Liść',description:'Fotosynteza, wymiana gazowa i parowanie wody. Aparaty szparkowe regulują wymianę.'}],
[{art:'moss',resident:'Mchu, opiekun polany',problem:'Polana wysycha. Odkryj, jak małe mchy pomagają zachować wodę.',effect:'Mchowa polana staje się zielona.',card:'Mchy',description:'Mają chwytniki, nie typowe korzenie. Zatrzymują wodę i wytwarzają zarodniki.'},{art:'fern',resident:'Feri, opiekunka paproci',problem:'Brama nie rozpoznaje swoich mieszkańców. Rozróżnij zarodniki i nasiona.',effect:'Paprocie rozwijają liście przy bramie.',card:'Paprocie',description:'Mają korzenie, łodygę i liście. Zarodniki powstają w zarodniach; nie mają kwiatów.'},{art:'flower',resident:'Feri, ogrodniczka',problem:'Ostatnie nasiona czekają na podróż. Pomóż kwiatom i owocom.',effect:'Ogród zakwita. Sześć krain odzyskuje blask.',card:'Kwiat, owoc i nasiono',description:'Zapylenie przenosi pyłek. Owoc chroni nasiona i może pomagać w ich rozsiewaniu.'}]
];
const H=(prompt,diagram,spots,correct,why,hint)=>({type:'hotspot',prompt,diagram,spots,correct,why,hint});
const S=(prompt,items,bins,correct,why,hint)=>({type:'sort',prompt,items,bins,correct,why,hint});
const EXTRA=[
[ C('Co się stanie z wnioskiem, jeśli w doświadczeniu zmienisz naraz światło i ilość wody?',['Nie ustalisz, który czynnik spowodował zmianę','Zawsze poznasz wpływ samego światła','Rośliny nie będą prowadzić czynności życiowych'],'Gdy zmienimy kilka czynników naraz, nie możemy przypisać wyniku jednemu z nich.','Porównaj warunki obu roślin.'), H('Dotknij grzybni na uproszczonym schemacie.','mushroom',[[50,28,'Kapelusz'],[50,61,'Trzon'],[26,90,'Strzępki pod ściółką']],[2],'Grzybnia to sieć strzępek. Kapelusz i trzon są częścią owocnika.','Szukaj sieci nitek, nie owocnika.'), C('Usuwamy partnera fotosyntetyzującego z porostu. Jakiej korzyści zabraknie grzybowi?',['Związków pokarmowych wytwarzanych przez partnera','Gotowych nasion paproci','Własnych chloroplastów grzyba'],'Partner fotosyntetyzujący wytwarza związki organiczne. Grzyb nie ma własnych chloroplastów.','Przypomnij sobie role obu partnerów.') ],
[ H('Gdzie w tym schemacie komórki roślinnej znajduje się jądro?','cell',[[29,41,'Fioletowy element'],[71,26,'Zielony element'],[54,53,'Niebieski zbiornik']],[0],'Fioletowy element to jądro. Chloroplast jest zielony, a wakuola jest dużym zbiornikiem.','Jądro nie jest ani magazynem wody, ani miejscem fotosyntezy.'), H('Wskaż chloroplast.','cell',[[29,41,'Fioletowy element'],[71,26,'Zielony element'],[54,53,'Niebieski zbiornik']],[1],'Chloroplast zawiera chlorofil. To miejsce fotosyntezy w komórce roślinnej.','Szukaj zielonego barwnika.'), C('W wielu komórkach rośliny zabrakło sprawnej błony. Co będzie zaburzone?',['Kontrola transportu do i z komórek','Wyłącznie przenoszenie pyłku','Wyłącznie rozsiewanie owoców'],'Błona komórkowa kontroluje przepływ substancji do komórki i z niej.','Wróć do funkcji granicy komórki.') ],
[ C('Roślina ma wodę i CO₂, lecz stoi długo w całkowitej ciemności. Co z fotosyntezą?',['Nie zachodzi bez światła','Zachodzi szybciej niż w świetle','Zamienia się w oddychanie'],'Fotosynteza wymaga energii światła. Oddychanie jest odrębnym procesem i może zachodzić w ciemności.','Którego źródła energii zabrakło?'), S('Posegreguj opisy: kto wytwarza pokarm, a kto pobiera gotowy?',['Zielona roślina w świetle','Grzyb rozkładający szczątki','Zwierzę zjadające liście'],['Samożywność','Cudzożywność'],[0,1,1],'Zielona roślina wytwarza związki organiczne. Grzyb i zwierzę korzystają z gotowych związków.','Miejsce pobierania substancji nie jest tym samym co wytwarzanie pokarmu.'), S('Przyporządkuj opisy do procesów.',['Wytwarzanie glukozy z wody i CO₂ z udziałem światła','Uwalnianie energii ze związków pokarmowych','Zachodzi w roślinie również w nocy'],['Fotosynteza','Oddychanie komórkowe'],[0,1,1],'Fotosynteza wytwarza związki pokarmowe przy wykorzystaniu światła. Oddychanie uwalnia z nich energię i zachodzi całą dobę.','Zwróć uwagę na kierunek: wytwarzanie pokarmu czy uwalnianie energii.') ],
[ C('Wirus trafia na wilgotny kamień bez żywych komórek. Czy sam zacznie się tam namnażać?',['Nie, potrzebuje żywej komórki gospodarza','Tak, sama wilgoć wystarcza','Tak, jeśli kamień jest zielony'],'Wirus nie namnaża się samodzielnie poza żywą komórką gospodarza.','Nie myl miejsca przebywania z miejscem namnażania.'), O('Ułóż uproszczone etapy podziału bakterii.',['Skopiowanie materiału genetycznego','Rozdzielenie kopii w komórce','Podział na dwie komórki'],'Podział bakterii poprzedza kopiowanie DNA. Potomne komórki otrzymują informację genetyczną.','Obie nowe komórki muszą otrzymać materiał genetyczny.'), C('Euglena znajduje się w świetle. Co umożliwia jej wytwarzanie pokarmu?',['Fotosynteza w chloroplastach','Korzenie pobierające gotowy cukier z gleby','Powstanie kwiatów'],'Euglena może fotosyntetyzować dzięki chloroplastom. Jest protistem, nie rośliną z korzeniem.','Zwróć uwagę na elementy komórki.') ],
[ C('Uszkodzono wiele włośników. Co może osłabnąć?',['Pobieranie wody i soli mineralnych','Przenoszenie pyłku przez owady','Wytwarzanie zarodników paproci'],'Włośniki zwiększają powierzchnię kontaktu korzenia z glebą. Ich uszkodzenie może utrudnić pobieranie substancji.','Pomyśl o powierzchni pobierającej.'), C('Przerwano tkanki przewodzące w łodydze. Co będzie zagrożone?',['Transport substancji między organami','Wyłącznie kolor płatków','Powstanie jądra komórkowego'],'Tkanki przewodzące zapewniają transport, m.in. wody z korzeni ku liściom.','Jaką rolę pełni szlak łodygowy?'), H('Wskaż aparaty szparkowe na uproszczonym schemacie.','leaf',[[48,24,'Wierzchołek blaszki'],[50,70,'Nerw liścia'],[79,73,'Dwie komórki i szczelina']],[2],'Aparat szparkowy ma komórki szparkowe i szczelinę. Reguluje wymianę gazową i parowanie.','Szukaj otworu o regulowanej szerokości.') ],
[ C('Mchowa poduszka zatrzymuje deszcz. Jaki może być efekt?',['Woda odpływa wolniej, a otoczenie dłużej pozostaje wilgotne','Mchy zaczynają tworzyć owoce','Każdy mech zamienia się w drzewo'],'Mchy zatrzymują wodę, pomagając utrzymywać wilgoć. Nie tworzą owoców.','Zwiąż budowę chłonnej poduszki z jej funkcją.'), S('Rozdziel rośliny według tego, czy tworzą nasiona.',['Paproć','Sosna','Jabłoń'],['Zarodnikowe','Nasienne'],[0,1,1],'Paproć wytwarza zarodniki. Sosna i jabłoń należą do roślin nasiennych; owoc tworzy jabłoń.','Nasiono i zarodnik to różne struktury.'), O('Ułóż uproszczoną drogę od zapylenia do rozsiania nasion.',['Przeniesienie pyłku na znamię słupka','Zapłodnienie','Rozwój nasion i owocu','Rozsianie nasion'],'Zapylenie poprzedza zapłodnienie. Po zapłodnieniu rozwijają się nasiona, a zalążnia uczestniczy w powstawaniu owocu.','Najpierw pyłek musi dotrzeć do słupka.') ]
];
EXTRA.forEach((extras,w)=>extras.forEach((q,n)=>{q.id='myko-extra-'+w+'-'+n;q.world=w;q.node=n;WORLDS[w].quests.push(q);ALL_QUESTIONS.push(q)}));
WORLDS.forEach((w,i)=>{w.missions=MISSIONS[i];w.palette=[['#c6ceac','#92b4a2'],['#d7c4d8','#a5bca0'],['#dfdb9e','#b2c897'],['#b5d7d2','#a9c4cf'],['#bdcca2','#94ad89'],['#bfd6ab','#9aacb8']][i];});
