'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',KEY='naukogramy.myko.v1'+(new URLSearchParams(location.search).has('qa')?'.qa':''),PEOPLE=['Aga','Gaba','Iga','Krzysiek'],E=MykoEngine;
let saved,raw;try{raw=localStorage.getItem(KEY);saved=JSON.parse(raw)}catch{}if(raw&&saved?.people&&saved.version!==2){try{if(!localStorage.getItem(KEY+'.backup-before-board'))localStorage.setItem(KEY+'.backup-before-board',raw)}catch{}}
saved=E.migrate(saved);if(!PEOPLE.includes(saved.person))saved.person='Aga';
let person=saved.person,wi=0,pos=0,motion=null,arrival=null,lastFrame=0,solved=false,draft=[],matched=[],optionOrder=[],audio=null,heroTimer=null,questWasOpen=false;
const reducedQuery=matchMedia('(prefers-reduced-motion:reduce)');
function profile(){return saved.people[person]||(saved.people[person]=E.blank())}
function persist(){saved.person=person;try{localStorage.setItem(KEY,JSON.stringify(saved))}catch{message('Zapis jest niedostępny w tej przeglądarce. Zostaw grę otwartą, aby zachować bieżącą przygodę.')}}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function completed(w,n){return profile().complete.includes(w+':'+n)}
function openWorld(w){return w===0||[0,1,2].every(n=>completed(w-1,n))}
function available(n){return completed(wi,n)||n===0||completed(wi,n-1)}
function allComplete(w){return[0,1,2].every(n=>completed(w,n))}
function message(s){$('map-message').textContent=s}
function el(name,attrs={},html=''){const n=document.createElementNS(NS,name);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);n.innerHTML=html;return n}
function sound(notes=[523,659]){if(!saved.sound)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();audio.resume();notes.forEach((freq,i)=>{const osc=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime+i*.1;osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.025,t+.015);gain.gain.exponentialRampToValueAtTime(.001,t+.18);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+.2)})}catch{}}
function updateWallet(){$('stars').textContent='✦ '+profile().stars}
function renderLandscape(){const w=WORLDS[wi],colors=w.palette;$('world').style.background='radial-gradient(ellipse at 50% 35%,'+colors[0]+','+colors[1]+')';$('landscape').innerHTML='<defs><clipPath id="board-clip"><rect x="12" y="12" width="976" height="776" rx="90"/></clipPath><linearGradient id="water" x2="1" y2="1"><stop stop-color="#acd1c9"/><stop offset="1" stop-color="#76a7b0"/></linearGradient></defs><g clip-path="url(#board-clip)"><image class="land-art" preserveAspectRatio="none" href="assets/krainy.webp" x="'+(-wi%3*1000)+'" y="'+(-Math.floor(wi/3)*800)+'" width="3000" height="1600"/><path d="M-50 130Q90 235 150 155T350 112T540 160T820 110T1070 200V-20H-50Z" fill="'+colors[1]+'" opacity=".75"/><path d="M-70 680Q100 800 320 749T700 750T1080 645V870H-70Z" fill="'+colors[1]+'" opacity=".8"/><path d="M-40 390Q130 295 238 357T433 482T695 604T1060 590" fill="none" stroke="#e7ebd0" stroke-width="90"/><path d="M-40 390Q130 295 238 357T433 482T695 604T1060 590" fill="none" stroke="url(#water)" stroke-width="64"/><path class="water-ripple" d="M22 375L64 363M95 351L131 354M239 362L280 383M394 453L422 477M713 605L762 616M862 613L904 612" stroke="#e5f3df" stroke-width="6" stroke-linecap="round" fill="none"/><ellipse cx="222" cy="514" rx="132" ry="116" fill="'+colors[0]+'"/><ellipse cx="517" cy="245" rx="135" ry="98" fill="'+colors[0]+'"/><ellipse cx="802" cy="457" rx="136" ry="108" fill="'+colors[0]+'"/></g>';
const decor=[['fern',40,70,.8],['mushroom',790,30,.65],['fern',15,515,.7],['flower',670,650,.65],['moss',790,680,.8],['mushroom',305,20,.55]];decor.forEach(([kind,x,y,s],i)=>{const g=el('g',{transform:'translate('+x+' '+y+') scale('+s+')',opacity:.8},'<g class="leaf-sway" stroke="#785c65" stroke-width="3">'+ART[wi===3?(i%2?'virus':'moss'):wi===1?(i%2?'cell':'flower'):kind]+'</g>');$('landscape').append(g)});for(let i=0;i<12;i++)$('landscape').append(el('circle',{cx:65+(i*83)%890,cy:100+(i*127)%620,r:3+i%3,fill:'#fff1be',class:'glow',style:'animation-delay:'+i*.3+'s'}));
$('trail').innerHTML='<path d="'+E.path+'" fill="none" stroke="#9e8b70" stroke-width="51" stroke-linecap="round" opacity=".35"/><path d="'+E.path+'" fill="none" stroke="#f0d8a2" stroke-width="43" stroke-linecap="round"/><path d="'+E.path+'" fill="none" stroke="#fff0cc" stroke-width="2" stroke-dasharray="3 18"/>';
// The walkway crosses the stream on a wooden bridge, keeping Myko above the water.
$('trail').append(el('g',{transform:'translate(385 448) rotate(-38)'},'<rect x="-31" y="-58" width="62" height="116" rx="8" fill="#be976d" stroke="#816650" stroke-width="3"/><path d="M-30-37H30M-30-16H30M-30 5H30M-30 26H30M-30 47H30" stroke="#866d56" stroke-width="4"/>'));
for(let s=0;s<E.length;s+=52){const p=E.at(s);$('trail').append(el('ellipse',{cx:p.x,cy:p.y,rx:15,ry:10,transform:'rotate('+p.angle+' '+p.x+' '+p.y+')',class:'trail-stone'+(s<=E.nodeS[profile().complete.filter(k=>k.startsWith(wi+':')).length-1]?' lit':'')}))}}
function updatePlaces(){const p=profile();updateWallet();$('chapter').textContent=person+' · '+[0,1,2].filter(n=>completed(wi,n)).length+'/3 odkrycia';$('world-name').textContent=WORLDS[wi].name;$('companion').textContent=WORLDS[wi].friend;$('story').textContent=allComplete(wi)?'Ta kraina odzyskała blask. Możesz wrócić do odkryć lub ruszyć dalej.':WORLDS[wi].story;$('places').replaceChildren();WORLDS[wi].missions.forEach((m,n)=>{const pt=E.at(E.nodeS[n]),done=completed(wi,n),state=done?'complete':available(n)?'available':'locked';const g=el('g',{class:'place '+state,transform:'translate('+pt.x+' '+(pt.y-130)+')','data-node':n,tabindex:0,role:'button','aria-label':WORLDS[wi].nodes[n]+' — '+(done?'ukończone':available(n)?'dostępne':'zamknięte'),'aria-disabled':!available(n)},'<ellipse class="place-plinth" cx="0" cy="20" rx="70" ry="25"/><g class="'+(done?'effect-on':'effect-off')+'" transform="translate(-73 -123) scale(.73)" stroke="#785c65" stroke-width="3" stroke-linejoin="round" stroke-linecap="round">'+ART[m.art]+'</g><text class="place-label" x="0" y="180" text-anchor="middle">'+WORLDS[wi].nodes[n]+'</text><text class="place-state" x="0" y="210" text-anchor="middle">'+(done?'✓ Odkryte':available(n)?'Pomóż mieszkańcowi':'Jeszcze zamknięte')+'</text><rect class="place-hit" x="-105" y="-120" width="210" height="365" rx="24"/>');g.addEventListener('click',()=>choosePlace(n));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choosePlace(n)}});$('places').append(g)});if(motion&&arrival!==null)$('places').children[arrival]?.classList.add('current');$('interact').textContent=allComplete(wi)?(wi<5?'Następna kraina →':'Wróć do Atlasu'):'Idź do przygody →';if(p.active&&!allComplete(wi))$('interact').textContent='Kontynuuj przygodę →'}
function storePosition(){profile().positions[wi]=pos;persist()}
function stopMotion(){motion=null;arrival=null;$('hero').classList.remove('walking');$('skip').hidden=true}
function closeQuest(){if(!$('quest').hidden){$('quest').hidden=true;$('play-layout')?.classList.remove('has-quest');storePosition()}questWasOpen=false}
function setWorld(w){if(!openWorld(w))return;stopMotion();closeQuest();wi=w;profile().world=w;pos=Math.max(0,Math.min(E.length,profile().positions[w]||0));renderLandscape();updatePlaces();positionHero();persist();message('Dotknij miejsca. Myko pójdzie po ścieżce.');}
function positionHero(){const p=E.at(pos);const flip=motion&&motion.to<pos?-1:1;$('hero').setAttribute('transform','translate('+p.x+' '+p.y+')');$('hero').style.setProperty('--direction',flip);}
function choosePlace(n){if(!available(n)){message('Najpierw pomóż poprzedniemu mieszkańcowi.');return}closeQuest();travelTo(E.nodeS[n],n)}
function travelTo(to,node=null){to=Math.max(0,Math.min(E.length,to));arrival=node;const distance=Math.abs(to-pos);motion={from:pos,to,start:performance.now(),duration:reducedQuery.matches?240:Math.min(4200,Math.max(450,distance*4.2))};$('skip').hidden=motion.duration<1800;updatePlaces();message(node===null?'Myko spaceruje po ścieżce.':'W drodze do: '+WORLDS[wi].nodes[node]);$('hero').classList.add('walking');}
function animate(now){const dt=Math.min((now-lastFrame)/1000,.05);lastFrame=now;if(motion){const t=Math.min(1,(now-motion.start)/motion.duration),previous=pos;pos=motion.from+(motion.to-motion.from)*E.ease(t);positionHero();const p=E.at(pos),slope=pos>=previous?1:-1;$('hero').querySelector('.hero-body').style.scale=slope+' 1';if(t>=1){const n=arrival;stopMotion();storePosition();if(n!==null)startQuest(n);else message('Myko czeka. Dotknij miejsca, aby pomóc mieszkańcowi.')}}requestAnimationFrame(animate)}
$('skip').onclick=()=>{if(motion){motion={from:pos,to:motion.to,start:performance.now(),duration:240};$('skip').hidden=true}};
$('board').addEventListener('pointerdown',e=>{if(e.target.closest('.place')||e.target.closest('#hero')||!$('quest').hidden)return;const pt=$('board').createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;const local=pt.matrixTransform($('board').getScreenCTM().inverse()),max=E.nodeS[[0,1,2].filter(available).at(-1)];const near=E.closest(local.x,local.y,max);if(Math.hypot(local.x-near.x,local.y-near.y)<95)travelTo(near.s);else message('Myko trzyma się ścieżki. Dotknij pola lub miejsca przygody.');});
function heroReact(){clearTimeout(heroTimer);$('hero').classList.remove('react');void $('hero').getBoundingClientRect();$('hero').classList.add('react');$('hero-mouth').setAttribute('d','M-5-20 Q1-8 7-20');message(['Hej! Jestem Myko. Dotknij miejsca — pójdziemy razem!','Mała pomyłka też prowadzi do odkrycia.','W Atlasie czekają Twoje odkrycia.'][Math.floor(Math.random()*3)]);sound([659,784]);heroTimer=setTimeout(()=>{$('hero').classList.remove('react');$('hero-mouth').setAttribute('d','M-5-20 Q1-13 7-20')},1100)}
$('hero').addEventListener('click',heroReact);$('hero').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();heroReact()}});
document.addEventListener('keydown',e=>{if(!['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName)&&!document.querySelector('dialog[open]')&&$('quest').hidden){const k=e.key.toLowerCase();if(['arrowright','arrowup','d','w','arrowleft','arrowdown','a','s'].includes(k)){e.preventDefault();const dir=['arrowright','arrowup','d','w'].includes(k)?1:-1;travelTo(Math.min(E.nodeS[[0,1,2].filter(available).at(-1)],pos+dir*90));}if(k==='e'){e.preventDefault();const n=[0,1,2].filter(available).sort((a,b)=>Math.abs(E.nodeS[a]-pos)-Math.abs(E.nodeS[b]-pos))[0];choosePlace(n)}}if(e.key==='Escape'&&!$('quest').hidden){closeQuest();message('Przygoda zapisana. Wróć do tego miejsca, aby kontynuować.')}});
function nextAdventure(){if(profile().active){const a=profile().active;if(openWorld(a.world)){setWorld(a.world);if(a.node===-1)startQuest(-1,a.ids);else choosePlace(a.node);return}}const n=[0,1,2].find(n=>available(n)&&!completed(wi,n));if(n!==undefined)choosePlace(n);else if(wi<5)setWorld(wi+1);else openBook()}
$('interact').onclick=nextAdventure;
function current(){const a=profile().active;return a&&ALL_QUESTIONS.find(q=>q.id===a.ids[a.step])}
function sessionKey(a){return a.world+':'+a.node}
function startQuest(n,ids){stopMotion();const p=profile(),key=wi+':'+n;let a=p.active;if(a&&!(a.world===wi&&a.node===n)&&!ids){p.sessions[sessionKey(a)]=a;a=null}if(ids&&a?.node===-1){/* Resume an existing review. */}else if(ids){if(a)p.sessions[sessionKey(a)]=a;a=null}else if(!a||a.world!==wi||a.node!==n)a=p.sessions[key]||null;
if(!a||!currentQuestionValid(a))a={ids:ids||WORLDS[wi].quests.filter(q=>q.node===n).map(q=>q.id),world:wi,node:n,step:0,tries:0,hinted:false,hintLevel:0,earned:0,first:0,mistakes:0,run:Date.now()+'-'+Math.random().toString(36).slice(2),draft:[],matched:[],solved:false};p.active=a;delete p.sessions[key];persist();round();$('quest').hidden=false;questWasOpen=true;setTimeout(()=>$('quest-close').focus({preventScroll:true}),0);message(n===-1?'Powtórka odkryć.':WORLDS[wi].missions[n].resident+' czeka na Twoją pomoc.');}
function currentQuestionValid(a){return Array.isArray(a.ids)&&a.step<a.ids.length&&a.ids.every(id=>ALL_QUESTIONS.some(q=>q.id===id))}
function round(){const a=profile().active,q=current();if(!q)return;draft=[...(a.draft||[])];matched=[...(a.matched||[])];solved=!!a.solved;optionOrder=q.options?shuffle(q.options.map((_,i)=>i)):[];const m=WORLDS[q.world].missions[q.node];$('resident-art').innerHTML=residentArt(q.world);$('resident-name').textContent=m.resident;$('quest-count').textContent=(a.node===-1?'Powtórka':WORLDS[a.world].nodes[a.node])+' · '+(a.step+1)+'/'+a.ids.length;$('question').textContent=q.prompt;$('task-story').textContent=m.problem;$('instruction').textContent={choice:'Wybierz jedną odpowiedź.',multi:'Wybierz wszystkie pasujące elementy.',order:'Dotykaj etapów po kolei. Ponowne dotknięcie usuwa etap.',link:'Dopasuj opis do każdego elementu.',sort:'Przy każdym opisie wybierz właściwą grupę.',hotspot:'Dotknij odpowiedniego numeru na schemacie.'}[q.type];$('diagram').replaceChildren();$('feedback').className='';$('feedback').textContent=solved?'Odkrycie zapisane. '+q.why:'';$('check').hidden=solved;$('next').hidden=!solved;$('hint').disabled=solved||(a.hintLevel||0)>=2;$('hint').textContent='Trop '+Math.min(2,(a.hintLevel||0)+1)+'/2';$('next').textContent=a.step+1===a.ids.length?'Ożyw to miejsce →':'Kolejna zagadka →';renderChoices();if(q.type==='hotspot')renderDiagram(q);$('quest-scroll').scrollTop=0;}
function saveDraft(){const a=profile().active;a.draft=[...draft];a.matched=[...matched];persist()}
function renderChoices(){const q=current();$('choices').replaceChildren();if(q.type==='link'){const options=shuffle([...new Set(q.pairs.map(p=>p[1]))]);q.pairs.forEach((pair,i)=>{const label=document.createElement('label');label.textContent=pair[0];const select=document.createElement('select');select.setAttribute('aria-label','Dobierz: '+pair[0]);const empty=document.createElement('option');empty.value='';empty.textContent='Wybierz…';select.append(empty);options.forEach(o=>{const op=document.createElement('option');op.value=o;op.textContent=o;select.append(op)});select.value=matched[i]||'';select.disabled=solved;select.onchange=()=>{matched[i]=select.value;saveDraft()};label.append(select);$('choices').append(label)})}else if(q.type==='sort'){q.items.forEach((item,i)=>{const row=document.createElement('div');row.className='sort-row';const title=document.createElement('strong');title.textContent=item;row.append(title);q.bins.forEach((bin,j)=>{const b=document.createElement('button');b.textContent=bin;b.setAttribute('aria-label',item+' — '+bin);b.setAttribute('aria-pressed',matched[i]===j);b.className=matched[i]===j?'selected':'';b.disabled=solved;b.onclick=()=>{matched[i]=j;saveDraft();renderChoices()};row.append(b)});$('choices').append(row)})}else if(q.type!=='hotspot'){optionOrder.forEach(i=>{const b=document.createElement('button');b.type='button';const span=document.createElement('span');span.className='number';span.textContent=q.type==='order'?(draft.includes(i)?draft.indexOf(i)+1:'·'):q.type==='multi'?(draft.includes(i)?'✓':'+'):'○';b.append(span,document.createTextNode(q.options[i]));b.setAttribute('aria-pressed',String(draft.includes(i)));b.disabled=solved;b.onclick=()=>{if(solved)return;if(q.type==='choice')draft=[i];else draft=draft.includes(i)?draft.filter(x=>x!==i):[...draft,i];saveDraft();renderChoices()};$('choices').append(b)})}}
function renderDiagram(q){$('diagram').innerHTML='<div class="bio-diagram"><svg viewBox="0 0 420 300" aria-label="Uproszczony schemat: '+q.diagram+'">'+diagramArt(q.diagram)+'</svg></div><p class="diagram-caption">Uproszczony schemat biologiczny. Numery są punktami wyboru.</p>';const box=$('diagram').firstChild;q.spots.forEach((spot,i)=>{const b=document.createElement('button');b.className='hotspot';b.style.left=spot[0]+'%';b.style.top=spot[1]+'%';b.textContent=i+1;b.setAttribute('aria-label','Punkt '+(i+1)+': '+spot[2]);b.setAttribute('aria-pressed',draft.includes(i));b.disabled=solved;b.onclick=()=>{draft=[i];saveDraft();renderDiagram(q)};box.append(b)})}
function check(){const p=profile(),a=p.active,q=current();if(!q||solved||a.solved)return;if(!E.ready(q,draft,matched)){$('feedback').textContent='Dokończ wybór. Możesz spokojnie się zastanowić.';return}const correct=E.evaluate(q,draft,matched),delta=E.award(p,a,q,correct);try{!KEY.endsWith('.qa')&&window.StudyActivity?.record(person,'myko:'+a.run+':'+q.id)}catch{}if(correct){solved=true;$('feedback').className='good';$('feedback').textContent=(delta?'Odkrycie! +'+delta+' iskier. ':'To odkrycie jest już zapisane. ')+q.why;$('check').hidden=true;$('next').hidden=false;$('hint').disabled=true;$('choices').querySelectorAll('button,select').forEach(b=>b.disabled=true);$('diagram').querySelectorAll('button').forEach(b=>b.disabled=true);sound([523,659,784]);}else{$('feedback').className='';$('feedback').textContent='Jeszcze nie. '+q.hint+' Popraw odpowiedź i spróbuj ponownie.';sound([330,294]);}persist();updateWallet();$('feedback').scrollIntoView({block:'nearest',behavior:reducedQuery.matches?'instant':'smooth'});}
function next(){if(!solved)return;const p=profile(),a=p.active;a.step++;a.tries=0;a.hinted=false;a.hintLevel=0;a.solved=false;a.draft=[];a.matched=[];if(a.step<a.ids.length){persist();round();return}if(a.node!==-1&&!completed(a.world,a.node))p.complete.push(a.world+':'+a.node);p.runs.push({name:a.node===-1?'Powtórka':WORLDS[a.world].name+' / '+WORLDS[a.world].nodes[a.node],at:new Date().toISOString(),first:a.first,total:a.ids.length,earned:a.earned});p.runs=p.runs.slice(-40);delete p.sessions[sessionKey(a)];p.active=null;persist();closeQuest();renderLandscape();updatePlaces();positionHero();const m=a.node===-1?null:WORLDS[a.world].missions[a.node];$('reward-art').innerHTML=objectArt(m?.art||'mushroom');$('reward-title').textContent=m?WORLDS[a.world].nodes[a.node]+' ożywa!':'Powtórka ukończona';$('reward-story').textContent=m?m.effect+(allComplete(a.world)?' '+WORLDS[a.world].reward+' zdobyta.':''):'Twoje odpowiedzi i odkrycia są zapisane w Atlasie.';$('reward-score').textContent=a.first+'/'+a.ids.length+' bez pomyłki · +'+a.earned+' nowych iskier';$('celebrate').showModal();sound([523,659,784,1047]);message(m?m.effect:'Powtórka ukończona.');}
$('hint').innerHTML='<span aria-hidden="true">☼</span> Trop 1/2';$('hint').onclick=()=>{const a=profile().active,q=current();if(!a||solved||(a.hintLevel||0)>=2)return;a.hinted=true;a.hintLevel=(a.hintLevel||0)+1;const first={choice:'Porównaj znaczenie odpowiedzi, a nie długość zdania.',multi:'Szukaj całego zestawu. Jedna poprawna odpowiedź może nie wystarczyć.',order:'Znajdź początek i skutek. Co musi wydarzyć się najpierw?',link:'Porównaj funkcję z budową lub nazwą każdego elementu.',sort:'Każdą rzecz przyporządkuj osobno; grupy mogą się powtarzać.',hotspot:'Przyjrzyj się kształtowi, położeniu i opisom punktów.'};$('feedback').textContent=(a.hintLevel===1?first[q.type]:q.hint)+' Odkrycie z tropem daje do 60 iskier.';$('hint').textContent='Trop 2/2';$('hint').disabled=a.hintLevel>=2;persist()};$('check').onclick=check;$('next').onclick=next;$('quest-close').onclick=()=>{closeQuest();message('Przygoda zapisana. Wróć do miejsca, aby ją kontynuować.')};
function worldMap(){questWasOpen=!$('quest').hidden;stopMotion();storePosition();$('world-list').replaceChildren();WORLDS.forEach((w,i)=>{const b=document.createElement('button');b.className='world-card'+(i===wi?' current':'')+(openWorld(i)?'':' locked');b.setAttribute('aria-label',w.name+' — '+(openWorld(i)?'otwarta':'zamknięta'));const count=[0,1,2].filter(n=>completed(i,n)).length;b.innerHTML='<div class="mini-world" style="--bx:'+(i%3*50)+'%;--by:'+(Math.floor(i/3)*100)+'%"></div><span class="info"><strong>'+w.name+'</strong><small>'+(openWorld(i)?count+'/3 miejsc odkrytych':'Najpierw ukończ poprzednią krainę')+'</small><progress max="3" value="'+count+'"></progress></span>';b.onclick=()=>{if(!openWorld(i)){message('Najpierw ukończ poprzednią krainę.');return}$('worlds').close();setWorld(i)};$('world-list').append(b)});$('worlds').showModal()}
$('world-picker').onclick=worldMap;
function openBook(){stopMotion();storePosition();const p=profile();$('book-title').textContent='Odkrycia: '+person;$('book-score').textContent=p.complete.length+'/18 przygód · '+Object.keys(p.facts).filter(k=>p.facts[k].best>0).length+'/'+ALL_QUESTIONS.length+' zagadek · '+p.stars+' iskier';$('collection').replaceChildren();WORLDS.forEach((w,i)=>w.missions.forEach((m,n)=>{const earned=completed(i,n);const card=document.createElement('article');card.className='discovery'+(earned?'':' locked');card.innerHTML=objectArt(m.art)+'<strong>'+(earned?m.card:'Nieodkryta karta')+'</strong><p>'+(earned?m.description:'Pomóż mieszkańcowi: '+w.nodes[n])+ '</p><small>'+w.name+' · '+(earned?'Zdobyta':'Czeka na odkrycie')+'</small>';$('collection').append(card)}));const weak=E.review(p,ALL_QUESTIONS);$('review').disabled=!weak.length;$('review').textContent=weak.length?'Powtórz zagadki do utrwalenia ('+weak.length+')':'Brak zagadek do utrwalenia';$('review').onclick=()=>{$('book').close();closeQuest();const ids=weak.map(q=>q.id).slice(0,8);startQuest(-1,ids)};$('records').replaceChildren();p.runs.slice(-6).reverse().forEach(r=>{const line=document.createElement('p');line.textContent=r.name+' · '+new Date(r.at).toLocaleDateString('pl-PL')+' · '+r.first+'/'+r.total+' bez pomyłki · +'+r.earned+' iskier';$('records').append(line)});$('notes').innerHTML=WORLDS.map(w=>'<section class="note"><h3>'+w.name+'</h3>'+w.quests.map(q=>'<p>'+q.why+'</p>').join('')+'</section>').join('');$('book').showModal()}
$('book-button').onclick=openBook;$('continue').onclick=()=>{$('celebrate').close();nextAdventure()};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('brand').onclick=()=>{stopMotion();storePosition();$('person').value=person;$('welcome').showModal()};
$('begin').onclick=()=>{closeQuest();person=$('person').value;const p=profile();wi=Math.max(0,Math.min(5,p.world||0));while(!openWorld(wi))wi--;persist();$('welcome').close();setWorld(wi);if(p.active&&currentQuestionValid(p.active)){wi=p.active.world;setWorld(wi);pos=E.nodeS[Math.max(0,p.active.node)]||0;positionHero();startQuest(p.active.node,p.active.node===-1?p.active.ids:undefined)}};
function soundLabel(){$('sound').setAttribute('aria-pressed',!!saved.sound);$('sound').setAttribute('aria-label',saved.sound?'Wyłącz dźwięki':'Włącz dźwięki');$('sound').textContent=saved.sound?'Dźwięk: wł.':'Dźwięk: wył.'}$('sound').onclick=()=>{saved.sound=!saved.sound;persist();soundLabel();if(saved.sound)sound([523])};soundLabel();
window.addEventListener('pagehide',()=>{profile().positions[wi]=pos;persist()});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(motion){const n=arrival,to=motion.to;motion={from:pos,to,start:performance.now(),duration:400};arrival=n}storePosition()}});
$('welcome-art').innerHTML=objectArt('mushroom');$('person').value=person;wi=Math.max(0,Math.min(5,profile().world||0));while(!openWorld(wi))wi--;setWorld(wi);requestAnimationFrame(animate);$('welcome').showModal();
