'use strict';
const C=(prompt,options,why,hint)=>({type:'choice',prompt,options,correct:[0],why,hint});
const M=(prompt,options,correct,why,hint)=>({type:'multi',prompt,options,correct,why,hint});
const O=(prompt,options,why,hint)=>({type:'order',prompt,options,correct:options.map((_,i)=>i),why,hint});
const L=(prompt,pairs,why,hint)=>({type:'link',prompt,pairs,why,hint});
const WORLDS=[
{name:'Grzybowy las',icon:'🍄',friend:'Myko · przewodniczka',story:'Latarnie grzybowej wioski gasną. Poznaj grzyby i zostań odkrywcą, żeby przywrócić ich blask.',reward:'Pieczęć odkrywcy',nodes:['Lupa Myko','Głodna grzybnia','Porostowy most'],icons:['🔬','🍂','🌉'],quests:[
C('Myko chce obejrzeć listek. Co jest obserwacją?',['Oglądanie listka i opisanie jego cech','Zmienianie ilości światła, aby sprawdzić wpływ na wzrost','Podanie roślinie różnych nawozów','Sprawdzenie wpływu temperatury w kilku hodowlach'],'Obserwacja polega na poznawaniu i opisywaniu obiektu bez celowego zmieniania badanego czynnika.','Czy odkrywca coś zmienia, czy tylko przygląda się obiektowi?'),
C('Dwie rośliny mają tyle samo wody. Jedna stoi w świetle, druga w ciemności. Co badamy?',['Wpływ światła na roślinę','Wpływ jednocześnie wszystkich czynników','Wpływ ilości wody','Wpływ rodzaju gleby'],'W doświadczeniu zmieniamy wybrany czynnik, a pozostałe warunki powinny być takie same. Tutaj zmieniono oświetlenie.','Znajdź jedyną różnicę między roślinami.'),
C('Okular powiększa 10 razy, obiektyw 4 razy. Jakie jest całkowite powiększenie?',['40 razy','14 razy','6 razy','100 razy'],'Powiększenie mikroskopu to iloczyn powiększeń okularu i obiektywu: 10 × 4 = 40.','Połącz dwa powiększenia przez mnożenie.'),
C('Myko potrzebuje pokarmu. Skąd grzyby biorą związki pokarmowe?',['Z gotowej materii organicznej','Wyłącznie z fotosyntezy','Wyłącznie z soli mineralnych','Wyłącznie ze światła'],'Grzyby są cudzożywne: korzystają z gotowych związków organicznych, np. z martwych szczątków lub od innych organizmów.','Grzyby nie mają chloroplastów.'),
O('Ułóż sposób zdobywania pokarmu przez grzybnię.',['Wydzielenie enzymów na pokarm','Rozkład pokarmu poza grzybem','Wchłonięcie produktów trawienia'],'Grzyby trawią pokarm na zewnątrz, a potem wchłaniają niewielkie cząsteczki.','Najpierw trzeba rozłożyć duże cząsteczki.'),
C('Co tworzy grzybnię?',['Strzępki','Korzenie','Płatki kwiatu','Nasiona'],'Grzybnia to zespół strzępek. Widoczny kapelusz z trzonem jest owocnikiem, czyli tylko częścią grzyba.','Pomyśl o cienkich niciach pod ściółką.'),
L('Dobierz mieszkańców do ich roli.',[['Drożdże','Pomagają spulchniać ciasto'],['Grzyby rozkładające szczątki','Uczestniczą w obiegu materii'],['Grzyb pasożytniczy','Żyje kosztem gospodarza']],'Grzyby mają różne role: rozkładają szczątki, pomagają w produkcji żywności lub wywołują choroby.','Nie wszystkie grzyby działają tak samo.'),
C('Która para tworzy porost?',['Grzyb i glon lub sinica','Grzyb i wirus','Paproć i bakteriofag','Mech i korzeń sosny'],'Porost tworzy grzyb oraz partner prowadzący fotosyntezę: glon lub sinica.','Jeden partner dostarcza związki pokarmowe z fotosyntezy.'),
C('Myko znalazła nieznany grzyb. Jaka decyzja jest właściwa?',['Nie zbierać go do jedzenia; identyfikacja wymaga pewności i wiedzy','Zjeść, jeśli jest kolorowy','Spróbować kawałek, żeby sprawdzić smak','Uznać go za jadalny, jeśli jadły go ślimaki'],'Nie rozpoznaje się jadalności grzybów po kolorze, smaku ani śladach żerowania zwierząt. Fantastyczne obrazki w grze nie służą do oznaczania gatunków.','Wygląd nie daje pewnej informacji o jadalności.')
]},
{name:'Miasto komórek',icon:'🧩',friend:'Komi · opiekunka komórek',story:'W mieście poprzestawiały się części komórek. Pomóż Komi przywrócić każdemu domowi właściwe wyposażenie.',reward:'Pieczęć komórki',nodes:['Brama komórki','Zielony domek','Miasto w mieście'],icons:['🫧','🌿','🧩'],quests:[
L('Połącz części komórki z funkcjami.',[['Błona komórkowa','Kontroluje transport do i z komórki'],['Jądro komórkowe','Zawiera informację genetyczną'],['Cytoplazma','Wypełnia komórkę i jest miejscem wielu procesów']],'Błona, cytoplazma i jądro pełnią różne funkcje. Nie każda komórka ma jądro.','Pomyśl: granica, instrukcje, wnętrze.'),
C('Która komórka nie ma jądra komórkowego?',['Bakteryjna','Zwierzęca w typowym szkolnym schemacie','Roślinna w typowym szkolnym schemacie','Grzybowa'],'Bakterie nie mają jądra, ale mają materiał genetyczny w komórce.','Brak jądra nie oznacza braku DNA.'),
M('Wybierz elementy występujące w komórce bakterii.',['Błona komórkowa','Cytoplazma','Materiał genetyczny','Chloroplast'],[0,1,2],'Bakterie mają błonę, cytoplazmę i materiał genetyczny. Nie mają chloroplastów.','Nie dodawaj organellum charakterystycznego dla roślin.'),
C('Który element pozwala zielonej komórce roślinnej prowadzić fotosyntezę?',['Chloroplast','Jądro','Błona komórkowa','Ściana komórkowa'],'W chloroplastach znajduje się chlorofil; zachodzi w nich fotosynteza.','Szukaj części zawierającej zielony barwnik.'),
M('Co odróżnia typową zieloną komórkę roślinną od zwierzęcej?',['Ściana komórkowa','Chloroplasty','Błona komórkowa','Cytoplazma'],[0,1],'Typowa zielona komórka roślinna ma ścianę i chloroplasty. Błonę i cytoplazmę mają oba typy komórek.','Szukaj różnic, nie wspólnych elementów.'),
C('Co gromadzi wodę i różne substancje w komórce roślinnej?',['Wakuola, czyli wodniczka','Chromosom','Obiektyw','Tkanka wzmacniająca'],'Duża wakuola magazynuje wodę i substancje oraz pomaga utrzymać napięcie komórki.','Pomyśl o wewnętrznym zbiorniku.'),
C('Który opis pasuje do komórki grzybowej?',['Ma jądro i ścianę, ale nie ma chloroplastów','Nie ma materiału genetycznego','Ma chloroplasty i jest zawsze samożywna','Nie jest komórką'],'Komórki grzybów mają jądro i ścianę komórkową, lecz nie mają chloroplastów.','Grzyb nie produkuje pokarmu dzięki fotosyntezie.'),
O('Ułóż poziomy budowy wielokomórkowego organizmu od najmniejszego.',['Komórka','Tkanka','Organ','Organizm'],'Komórki o podobnej budowie i funkcji tworzą tkanki; z tkanek powstają organy, które współpracują w organizmie.','Zacznij od podstawowej jednostki budowy.'),
C('Co jest przykładem organizmu jednokomórkowego?',['Bakteria','Dąb','Paproć','Człowiek'],'Jedna komórka bakterii wykonuje czynności całego organizmu.','Czy cały organizm mieści się w jednej komórce?')
]},
{name:'Zielona energia',icon:'☀️',friend:'Lumi · strażniczka liści',story:'Młyn Lumi stanął. Dobierz warunki fotosyntezy i odróżnij wytwarzanie pokarmu od zdobywania energii.',reward:'Pieczęć energii',nodes:['Słoneczny młyn','Pokarm dla lasu','Nocna latarnia'],icons:['☀️','🥬','🌙'],quests:[
M('Dostarcz substancje zużywane w fotosyntezie.',['Woda','Dwutlenek węgla','Tlen','Glukoza'],[0,1],'W fotosyntezie powstają związki pokarmowe z wody i dwutlenku węgla. Potrzebne są też światło i chlorofil.','Rozróżnij to, co roślina pobiera, od tego, co wytwarza.'),
C('Skąd pochodzi energia potrzebna do fotosyntezy?',['Ze światła','Z ziemi jako gotowy pokarm','Wyłącznie z tlenu','Z ciemności'],'Rośliny wykorzystują energię światła do wytwarzania związków pokarmowych.','Co zasila zielony młyn w dzień?'),
M('Wybierz produkty fotosyntezy.',['Glukoza','Tlen','Woda','Dwutlenek węgla'],[0,1],'W szkolnym schemacie produktami fotosyntezy są glukoza i tlen.','Produkty to to, co powstaje w procesie.'),
L('Dobierz sposób odżywiania.',[['Zielona roślina','Samożywność'],['Zwierzę','Cudzożywność'],['Grzyb','Cudzożywność']],'Rośliny wytwarzają związki pokarmowe w fotosyntezie. Zwierzęta i grzyby korzystają z gotowych związków organicznych.','Dwa organizmy mogą mieć ten sam sposób odżywiania.'),
C('Czy sole mineralne pobrane z gleby są gotowym pokarmem rośliny?',['Nie; roślina wytwarza związki pokarmowe, m.in. w fotosyntezie','Tak; roślina nie musi wytwarzać związków organicznych','Tak; zastępują energię światła','Nie; rośliny w ogóle ich nie potrzebują'],'Sole mineralne są potrzebne do prawidłowego funkcjonowania, ale nie zastępują wytwarzania związków pokarmowych.','Potrzebna substancja nie zawsze jest pokarmem.'),
C('Roślinożerca je liście. Jaką ma rolę w zdobywaniu pokarmu?',['Pobiera gotową materię organiczną','Sam wytwarza pokarm z dwutlenku węgla','Nie potrzebuje substancji pokarmowych','Jest samożywny dzięki liściom'],'Roślinożercy są cudzożywni, mimo że żywią się roślinami.','Liczy się sposób zdobywania pokarmu, nie jego kolor.'),
C('Po co komórki przeprowadzają oddychanie?',['Aby uwalniać energię ze związków pokarmowych','Aby wyłącznie pobierać wodę','Aby zastąpić wszystkie inne czynności życiowe','Aby zawsze wytwarzać glukozę ze światła'],'Oddychanie komórkowe uwalnia energię ze związków pokarmowych. Nie jest tym samym co wentylacja płuc.','Oddziel oddychanie komórki od wykonywania wdechu.'),
M('Wybierz substancje potrzebne w uproszczonym schemacie oddychania tlenowego.',['Glukoza','Tlen','Chlorofil','Światło'],[0,1],'W oddychaniu tlenowym glukoza jest rozkładana z udziałem tlenu, a energia staje się dostępna dla komórki.','Ten proces zachodzi także w ciemności.'),
C('Czy roślina oddycha w nocy?',['Tak, oddychanie zachodzi w dzień i w nocy','Nie, rośliny nigdy nie oddychają','Nie, oddycha tylko w świetle','Tak, ale wyłącznie przez płuca'],'Rośliny oddychają przez całą dobę. Fotosynteza wymaga światła, oddychanie komórkowe nie.','Nie utożsamiaj oddychania z fotosyntezą.')
]},
{name:'Kropla mikroświata',icon:'🦠',friend:'Bibi · mieszkanka kropli',story:'Bibi organizuje spotkanie mikromieszkańców. Pomóż ich rozpoznać — bakteria, protist i wirus nie są tym samym.',reward:'Pieczęć mikroświata',nodes:['Wirusowy gość','Bakterie w pracy','Wodna wyprawa'],icons:['💜','🦠','💧'],quests:[
C('Dlaczego wirusa nie zaliczamy do organizmów komórkowych?',['Nie ma budowy komórkowej','Jest zawsze większy od grzyba','Każdy wirus ma korzeń','Każdy wirus prowadzi fotosyntezę'],'Wirusy nie mają budowy komórkowej ani własnego metabolizmu. Namnażają się w komórkach gospodarza.','Nie oceniaj po fantastycznej buzi postaci.'),
C('Czego wirus potrzebuje do namnażania?',['Żywej komórki gospodarza','Wyłącznie wilgotnej skały','Samych soli mineralnych','Własnego kwiatu'],'Wirus wykorzystuje żywą komórkę gospodarza. Nie namnaża się sam jak bakteria.','Wirus musi wykorzystać cudzą komórkę.'),
C('Która choroba ma przyczynę wirusową?',['Grypa','Grzybica','Tężec','Salmonelloza'],'Grypę wywołują wirusy. Grzybica jest wywoływana przez grzyby, a tężec i salmonelloza przez bakterie.','Odróżnij trzy różne grupy patogenów.'),
M('Wybierz korzystne działania bakterii.',['Udział w produkcji jogurtu','Rozkład martwych szczątków','Pomoc w funkcjonowaniu przewodu pokarmowego','Wywoływanie każdej choroby wirusowej'],[0,1,2],'Wiele bakterii jest pożytecznych. Nie każda bakteria wywołuje chorobę, a choroby wirusowe nie są bakteryjne.','Szukaj działań przydatnych ludziom lub przyrodzie.'),
C('Jak najczęściej rozmnażają się bakterie?',['Przez podział komórki','Przez wytwarzanie kwiatów','Przez nasiona','Przez składanie jaj'],'Bakteria kopiuje materiał genetyczny i dzieli się na dwie komórki.','Cały organizm bakterii jest jedną komórką.'),
C('Które działanie ogranicza przenoszenie wielu drobnoustrojów?',['Mycie rąk','Jedzenie nieumytej żywności','Picie wody z nieznanego źródła','Dzielenie się każdym używanym ręcznikiem'],'Higiena rąk ogranicza przenoszenie wielu drobnoustrojów. Różne zakażenia wymagają różnych sposobów zapobiegania.','Zwróć uwagę na przenoszenie drobnoustrojów między powierzchniami.'),
L('Dopasuj protista do sposobu poruszania.',[['Pantofelek','Rzęski'],['Ameba','Nibynóżki'],['Euglena','Wić']],'Pantofelek ma rzęski, ameba tworzy nibynóżki, a euglena porusza się dzięki wici.','Wyobraź sobie liczne krótkie włoski, wypustki i długą nitkę.'),
C('Co odróżnia protista od bakterii?',['Komórka protista ma jądro','Protist nigdy nie ma komórki','Bakteria zawsze ma chloroplasty','Protisty to wyłącznie zwierzęta wielokomórkowe'],'Protisty mają komórki z jądrem. Bakterie nie mają jądra komórkowego.','Porównaj budowę ich komórek.'),
C('Euglena w świetle może wytwarzać pokarm. Który element jej w tym pomaga?',['Chloroplasty','Korzeń','Kwiat','Kapelusz'],'Euglena ma chloroplasty umożliwiające fotosyntezę. Nie jest rośliną z korzeniem i kwiatem.','Szukaj elementu znanego z zielonej komórki.')
]},
{name:'Podziemna sieć',icon:'🌱',friend:'Korri · strażnik korzeni',story:'Korri ma przerwany szlak wody. Odbuduj organy i tkanki, by krople dotarły do liści.',reward:'Pieczęć rośliny',nodes:['Stacja korzeni','Łodygowy szlak','Liściasta wieża'],icons:['🌱','🌳','🍃'],quests:[
M('Jakie są podstawowe funkcje korzenia?',['Pobieranie wody i soli mineralnych','Umocowanie rośliny w podłożu','Zapylanie kwiatów','Produkcja nasion'],[0,1],'Korzenie pobierają wodę i sole mineralne oraz utrzymują roślinę w podłożu. Niektóre magazynują substancje.','Szukaj funkcji potrzebnych pod ziemią.'),
C('Po co korzeniowi włośniki?',['Zwiększają powierzchnię pobierania wody i soli mineralnych','Tworzą płatki kwiatów','Roznoszą nasiona','Są organami lotu'],'Włośniki to wydłużone komórki skórki korzenia zwiększające powierzchnię kontaktu z podłożem.','Porównaj małą powierzchnię z dużą.'),
L('Dobierz tkanki do zadań.',[['Twórcza','Umożliwia wzrost dzięki podziałom komórek'],['Okrywająca','Chroni powierzchnię rośliny'],['Przewodząca','Transportuje substancje']],'Tkanki roślinne różnią się funkcją: twórcze odpowiadają za wzrost, okrywające chronią, a przewodzące transportują.','Szukaj znaczenia nazw tkanek.'),
C('Dlaczego roślinie potrzebna jest łodyga?',['Utrzymuje organy nadziemne i przewodzi substancje','Zawsze zastępuje wszystkie korzenie','Wyłącznie tworzy zarodniki','Służy wyłącznie do zapylania'],'Łodyga podtrzymuje liście, kwiaty i owoce oraz umożliwia transport substancji między organami.','Pomyśl o podporze i szlaku transportowym.'),
O('Poprowadź wodę pobraną z gleby do liścia.',['Korzeń','Łodyga','Liść'],'Woda i sole mineralne są pobierane przez korzeń i transportowane przez łodygę do liści.','Zacznij od organu mającego kontakt z glebą.'),
C('Która tkanka pomaga roślinie utrzymać kształt i wytrzymałość?',['Wzmacniająca','Nerwowa','Mięśniowa','Wyłącznie tkanka twórcza'],'Tkanki wzmacniające zwiększają wytrzymałość rośliny. Tkanki mięśniowa i nerwowa są charakterystyczne dla zwierząt.','Nazwa wiąże się z mechaniczną podporą.'),
M('Wybierz podstawowe funkcje liści.',['Fotosynteza','Wymiana gazowa','Parowanie wody','Pobieranie wody z gleby przez włośniki'],[0,1,2],'Liście prowadzą fotosyntezę, wymieniają gazy i uczestniczą w parowaniu wody. Włośniki należą do korzenia.','Nie przenoś funkcji korzenia do liścia.'),
C('Które struktury w skórce liścia regulują wymianę gazową?',['Aparaty szparkowe','Zarodnie','Nasiona','Płatki korony'],'Aparaty szparkowe umożliwiają wymianę gazową i wpływają na parowanie wody.','Szukaj otworów o regulowanej szerokości.'),
C('Gdzie w liściu zachodzi dużo fotosyntezy?',['W miękiszu zawierającym chloroplasty','Wyłącznie w martwych częściach ściany','Wyłącznie w zarodniach','Wyłącznie w nasionach'],'Miękisz asymilacyjny zawiera chloroplasty i jest miejscem intensywnej fotosyntezy.','Szukaj tkanki z zielonymi organellami.')
]},
{name:'Dolina paproci',icon:'🌿',friend:'Feri · opiekunka doliny',story:'Brama doliny czeka na ostatnią pieczęć. Poznaj mchy, paprocie i rośliny nasienne, by las znów zakwitł.',reward:'Pieczęć różnorodności',nodes:['Mchowa polana','Paprociowa brama','Ogród nasion'],icons:['🌱','🌿','🌸'],quests:[
C('Jak mchy przytwierdzają się do podłoża?',['Za pomocą chwytników','Za pomocą typowych korzeni jak u dębu','Za pomocą kwiatów','Za pomocą owoców'],'Mchy mają chwytniki, a nie typowe korzenie. Pobierają wodę także powierzchnią ciała.','Nie przenoś budowy drzewa na mech.'),
C('Dlaczego mchy są ważne dla wilgotności środowiska?',['Zatrzymują wodę i ograniczają jej szybki odpływ','Zawsze osuszają teren','Nie mają kontaktu z wodą','Wytwarzają plastikowe zbiorniki'],'Mchy mogą gromadzić wodę, pomagając utrzymywać wilgoć w środowisku.','Pomyśl o chłonnej poduszce.'),
C('Co znajduje się w zarodni mchu?',['Zarodniki','Nasiona','Owoce','Płatki kwiatów'],'Mchy rozmnażają się przy udziale zarodników. Nie tworzą kwiatów, owoców ani nasion.','Nie myl zarodnika z nasieniem.'),
C('Co można zobaczyć na spodniej stronie wielu liści paproci?',['Kupki zarodni','Owoce z nasionami','Kwiaty','Korzenie przybyszowe każdego liścia'],'Na spodniej stronie liści wielu paproci znajdują się kupki zarodni, w których powstają zarodniki.','Paproć nie jest rośliną kwiatową.'),
M('Wybierz organy paproci.',['Korzenie','Łodyga, często w postaci kłącza','Liście','Kwiaty'],[0,1,2],'Paprocie mają korzenie, łodygę i liście. Nie tworzą kwiatów, owoców ani nasion.','Szukaj organów rośliny zarodnikowej.'),
L('Dobierz roślinę do grupy.',[['Sosna','Nagonasienne'],['Jabłoń','Okrytonasienne'],['Paproć','Rośliny zarodnikowe']],'Sosna wytwarza nasiona niezamknięte w owocu. Jabłoń ma kwiaty i owoce, paproć rozmnaża się przez zarodniki.','Sprawdź, czy roślina tworzy owoc, nasiona czy zarodniki.'),
L('Połącz części kwiatu z ich rolą.',[['Pręcik','Wytwarza pyłek'],['Słupek','Zawiera zalążki w zalążni'],['Płatki korony','Mogą przywabiać zapylacze']],'Pręciki wytwarzają pyłek, w zalążni słupka są zalążki, a barwne płatki często przywabiają zapylacze.','Szukaj funkcji poszczególnych części kwiatu.'),
C('Na czym polega zapylenie u roślin okrytonasiennych?',['Na przeniesieniu pyłku na znamię słupka','Na połączeniu komórek rozrodczych','Na rozsianiu zarodników paproci','Na pobraniu wody przez korzeń'],'Zapylenie to przeniesienie pyłku na znamię słupka. Zapłodnienie jest innym, późniejszym procesem.','Przeniesienie pyłku i połączenie komórek to różne etapy.'),
L('Dobierz sposób rozsiewania do cechy owocu.',[['Skrzydlaki klonu','Wiatr'],['Mięsiste owoce','Zwierzęta zjadające owoce'],['Owoce z haczykami','Zaczepianie o sierść']],'Owoce i nasiona mają różne przystosowania do rozsiewania: skrzydełka, mięsisty pokarm lub haczyki.','Wyobraź sobie, co pomaga owocowi przemieścić się.')
]}
];
WORLDS.forEach((w,wi)=>w.quests.forEach((q,qi)=>{q.id='myko-'+wi+'-'+qi;q.world=wi;q.node=Math.floor(qi/3)}));
const ALL_QUESTIONS=WORLDS.flatMap(w=>w.quests);
