'use strict';
const MykoTrip=(()=>{
 const forms=[{id:'myko',name:'Myko',need:0,power:'Iskra odkrywcy',description:'Pierwszy przyjaciel lasu. Każde nowe rozwiązanie powiększa kapelusz.'},{id:'kania',name:'Kania',need:3,power:'Sokoli wzrok',description:'Raz w pokoju podświetla miejsca ukrytych wskazówek.'},{id:'kozak',name:'Kozak',need:6,power:'Leśny krok',description:'Spacer trwa krócej, także kiedy Myko jest osłabiony.'},{id:'muchomor',name:'Muchomor',need:9,power:'Zarodnikowa tarcza',description:'Raz na krainę osłania przed magicznym zagrożeniem bez zużycia eliksiru.'}];
 const ingredients={dew:'Kropla rosy',leaf:'Świetlisty liść',spore:'Zarodnik blasku'};
 const recipes=[{id:'mist',name:'Osłona mgły',cost:{dew:1,leaf:1},description:'Chroni przed jednym spotkaniem w ruinach.'},{id:'glow',name:'Osłona blasku',cost:{spore:1,dew:1},description:'Także jedno chronione spotkanie. Inna receptura, ta sama siła.'},{id:'forest',name:'Osłona lasu',cost:{leaf:1,spore:1},description:'Wykorzystaj składniki, których masz najwięcej.'}];
 const rooms=[
 [{name:'Domek leśnej badaczki',scene:'study',parts:['Soczewka','Źródło światła','Stolik preparatu'],clues:['Ślad na biurku prowadzi do soczewki.','Pod liściem schowano lampkę.','Szuflada kryje stolik preparatu.'],build:'Złóż stanowisko obserwacji',goal:'Uruchom lupę, porównując obserwację z doświadczeniem.'},{name:'Domek w korzeniu',scene:'root',parts:['Strzępka','Enzym','Pokarm do wchłonięcia'],clues:['Przy korzeniu widać cienką nitkę.','Słoiczek zawiera enzym.','Pod ściółką kryją się produkty trawienia.'],build:'Odtwórz drogę odżywiania grzyba',goal:'Nitki połączą się, kiedy wyjaśnisz, jak grzyb zdobywa pokarm.'},{name:'Warsztat porostowego mostu',scene:'bridge',parts:['Grzyb','Partner fotosyntetyzujący','Współpraca'],clues:['Na belce czeka karta grzyba.','W oknie błyszczy zielony partner.','Skrzynia zawiera znak współpracy.'],build:'Złóż znak porostu',goal:'Poznaj role partnerów, aby przywrócić most.'}],
 [{name:'Wieża komórek',scene:'cell',parts:['Błona','Cytoplazma','Jądro'],clues:['Drzwi przypominają granicę komórki.','W zbiorniku znajduje się cytoplazma.','Fioletowa skrzynka skrywa jądro.'],build:'Odbuduj model komórki zwierzęcej',goal:'Dobierz funkcje części, aby otworzyć wieżę.'},{name:'Zielona oranżeria',scene:'cell',parts:['Ściana','Chloroplast','Wakuola'],clues:['Twarda obręcz leży pod donicą.','Zielone pudełko skrywa chloroplast.','Błękitny zbiornik to model wakuoli.'],build:'Uzupełnij zieloną komórkę',goal:'Rozpoznaj wyposażenie komórki roślinnej.'},{name:'Miasto pod mikroskopem',scene:'city',parts:['Komórka','Tkanka','Organ'],clues:['Najmniejszy klocek czeka przy oknie.','Paczka podobnych komórek leży na stole.','Model organu jest w szafce.'],build:'Złóż poziomy budowy',goal:'Zbuduj organizm od małych części do większych.'}],
 [{name:'Słoneczna maszynownia',scene:'mill',parts:['Woda i CO₂','Światło i chlorofil','Glukoza i tlen'],clues:['Butelka i karta gazu leżą na ławie.','Witraż kieruje światło ku zielonym częściom.','Skrzynka przechowuje karty produktów.'],build:'Połącz wejście, warunki i produkty',goal:'Wiedza o fotosyntezie uruchomi koło młyna.'},{name:'Spichlerz leśnego ogrodu',scene:'garden',parts:['Roślina wytwarza pokarm','Grzyb pobiera gotowy pokarm','Zwierzę zjada pokarm'],clues:['W donicy czeka karta rośliny.','Pod liściem kryje się karta grzyba.','W koszu znajdziesz kartę zwierzęcia.'],build:'Odbuduj tablicę odżywiania',goal:'Rozróżnij wytwarzanie i pobieranie pokarmu.'},{name:'Latarnia o zmierzchu',scene:'lamp',parts:['Związki pokarmowe','Oddychanie komórkowe','Uwolniona energia'],clues:['Skrzynia mieści kartę pokarmu.','Na ścianie wisi karta procesu.','Przy latarni jest karta energii.'],build:'Połącz źródło, proces i skutek',goal:'Oddychanie działa w dzień i w nocy. Wyjaśnij, jak zasila komórki.'}],
 [{name:'Opuszczone laboratorium',scene:'lab',hazard:true,parts:['Materiał genetyczny','Białkowa osłona','Komórka gospodarza'],clues:['Fiolka skrywa kartę materiału genetycznego.','Pudełko zawiera model kapsydu.','Pod mikroskopem jest karta gospodarza.'],build:'Złóż tablicę wirusów',goal:'Model gospodarza jest obok wirusa, nie jest częścią jego budowy.'},{name:'Pracownia przyjaznych bakterii',scene:'lab',parts:['Komórka bakterii','Podział','Dwie komórki potomne'],clues:['Bibi zostawiła model komórki.','Instrukcja podziału leży w książce.','Na półce czekają dwa modele potomne.'],build:'Odtwórz opowieść o podziale',goal:'Bibi pomaga w fermentacji. Nie każda bakteria wywołuje choroby.'},{name:'Przystań w kropli',scene:'boat',hazard:true,parts:['Ameba: nibynóżki','Pantofelek: rzęski','Euglena: wić'],clues:['W wodzie ukryto kartę ameby.','Pod mostkiem jest karta pantofelka.','W łódce leży karta eugleny.'],build:'Złóż przewodnik po mikromieszkańcach',goal:'Rozpoznaj protisty i ich narządy ruchu. Zagrożeniem jest fabularny cień, nie każdy protist.'}],
 [{name:'Podziemna stacja kropli',scene:'root',parts:['Włośniki','Korzeń','Woda i sole mineralne'],clues:['Na ziemi widać delikatne włoski.','Przy ścianie jest model korzenia.','Błękitna skrzynia zawiera karty pobieranych substancji.'],build:'Odbuduj stanowisko korzenia',goal:'Połącz budowę korzenia z pobieraniem wody.'},{name:'Winda w łodydze',scene:'tower',parts:['Korzeń','Tkanki przewodzące','Liście'],clues:['Przy wejściu leży karta korzenia.','W szybie ukryto przewody.','Na górnej półce czekają liście.'],build:'Złóż drogę wody ku liściom',goal:'Wiedza o tkankach naprawi transport.'},{name:'Pokój zielonych okien',scene:'garden',parts:['Blaszka liścia','Nerwy liścia','Aparaty szparkowe'],clues:['Na stole jest model blaszki.','W szufladzie leży mapa nerwów.','Okno skrywa model komórek szparkowych.'],build:'Odbuduj przewodnik po liściu',goal:'Przywróć wymianę gazową i przypomnij funkcje liścia.'}],
 [{name:'Chata mchowego opiekuna',scene:'root',parts:['Chwytniki','Zatrzymywanie wody','Zarodniki'],clues:['Pod poduszką mchu są chwytniki.','W miseczce jest karta wody.','W kopercie ukryto kartę zarodników.'],build:'Złóż album mchów',goal:'Wyjaśnij, jak mchy żyją i pomagają otoczeniu.'},{name:'Paprociowa brama',scene:'garden',parts:['Korzeń, łodyga i liście','Zarodnie','Zarodniki'],clues:['Pod liściem leży model organów.','Na odwrocie liścia jest karta zarodni.','W skrzyni czeka karta zarodników.'],build:'Złóż album paproci',goal:'Odróżnij zarodniki od nasion.'},{name:'Ogród ostatniego nasiona',scene:'garden',parts:['Zapylenie','Zapłodnienie','Nasiona i owoc'],clues:['Kwiat skrywa kartę pyłku.','W książce jest karta zapłodnienia.','W koszu czekają nasiona i owoc.'],build:'Ułóż historię rośliny kwiatowej',goal:'Otwórz ogród i przygotuj nasiona do podróży.'}]
 ];
 function init(p){const x=p.expedition||(p.expedition={});x.version=1;x.rooms=x.rooms||{};x.maps=x.maps||{};x.claimed=x.claimed||[];x.fragments=x.fragments||[];x.secret=x.secret||[];x.inventory=x.inventory||{dew:0,leaf:0,spore:0};for(const k of Object.keys(ingredients))if(!Number.isFinite(x.inventory[k])||x.inventory[k]<0)x.inventory[k]=0;x.potions=x.potions||[];x.hazards=x.hazards||[];x.powers=x.powers||[];x.form=x.form||'myko';x.condition=x.condition==='weak'?'weak':'well';x.armed=!!x.armed;for(const key of p.complete){if(/^\d:[0-2]$/.test(key)){claim(p,key);const r=room(p,key);r.found=[0,1,2];r.placed=[0,1,2];}}if(!unlocked(p).some(f=>f.id===x.form))x.form='myko';return x;}
 function room(p,key){const x=p.expedition;return x.rooms[key]||(x.rooms[key]={found:[],placed:[],seen:false,power:false});}
 function claim(p,key){const x=p.expedition;if(x.claimed.includes(key))return false;x.claimed.push(key);if(!x.fragments.includes(key))x.fragments.push(key);x.inventory[['dew','leaf','spore'][Number(key.split(':')[1])]]++;return true;}
 function find(p,key,i){const r=room(p,key);if(r.found.includes(i)||i<0||i>2)return false;r.found.push(i);return true;}
 function place(p,key,i,slot){const r=room(p,key);if(!r.found.includes(i)||i!==slot||r.placed.includes(i))return false;r.placed.push(i);return true;}
 function assembled(p,key){return room(p,key).placed.length===3;}
 function unlocked(p){return forms.filter(f=>p.complete.length>=f.need);}
 function discoveries(p){return Object.values(p.facts).filter(f=>f.best>0).length;}
 function size(p){return 1+Math.min(72,discoveries(p))*.0035;}
 function craft(p,id){const x=p.expedition,r=recipes.find(r=>r.id===id);if(!r||!Object.entries(r.cost).every(([k,v])=>x.inventory[k]>=v))return false;for(const[k,v]of Object.entries(r.cost))x.inventory[k]-=v;x.potions.push(id);return true;}
 function arm(p){const x=p.expedition;if(x.armed||!x.potions.length)return false;x.potions.shift();x.armed=true;return true;}
 function enterHazard(p,key){const x=p.expedition;if(x.hazards.includes(key))return 'visited';x.hazards.push(key);const world=key.split(':')[0],power='shield:'+world;if(x.armed){x.armed=false;return 'protected';}if(x.form==='muchomor'&&!x.powers.includes(power)){x.powers.push(power);return 'power';}x.condition='weak';return 'weak';}
 function arrangeMap(p,w,piece,slot){const x=p.expedition;if(!x.fragments.includes(w+':'+piece)||piece!==slot)return false;const map=x.maps[w]||(x.maps[w]=[]);if(map.includes(slot))return false;map.push(slot);return true;}
 function mapReady(p,w){return (p.expedition.maps[w]||[]).length===3;}
 function secret(p,w){const x=p.expedition;if(x.secret.includes(w)||!mapReady(p,w)||![0,1,2].every(n=>x.fragments.includes(w+':'+n)))return false;x.secret.push(w);x.inventory.spore++;x.inventory.dew++;return true;}
 return{forms,ingredients,recipes,rooms,init,room,claim,find,place,assembled,unlocked,discoveries,size,craft,arm,enterHazard,arrangeMap,mapReady,secret};
})();
if(typeof module!=='undefined')module.exports=MykoTrip;
